### ISSUE TITLE
HTTPS not detected properly

### ISSUE THREAD

**Issue by mobamoba** [marius-wieschollek/passwords-webextension#10]
The picture explains it all. I get an warning that I need to be HTTPS to use the app but as you can see I am HTTPS. How do I fix this? Thanks

![untitled](https://user-images.githubusercontent.com/11135869/39959423-5e85d7b6-55df-11e8-9180-83dfa645dcc2.png)

**Comment by marius-wieschollek** [comment]
If you have the latest version from the app store installed, passwords uses the https detection from Nextcloud itself. In some setups Nextcloud requires additional configuration to detect https correctly. Take a look at the [manual](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/security_setup_warnings.html#you-are-accessing-this-site-via-http) to find a solution for your setup.

Note: This is the bug tracker for the browser extension. The bug tracker for the app is [here](https://github.com/marius-wieschollek/passwords)

**Comment by mobamoba** [comment]
Sorry about that. I thought the HTTPS detection was being generated by the app. I'll report it in the main Nextcloud forum instead.

**Comment by marius-wieschollek** [comment]
The error message is generated by the app. If you're using a proxy setup, you need to configure your setup like in the [manulal to make sure nextcloud will detect it properly](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/reverse_proxy_configuration.html)
