### ISSUE TITLE
Custom fields issue

### ISSUE THREAD

**Issue by Belface** [marius-wieschollek/passwords-webextension#100]
**### System Information**
- Extension Version: 1.9.1.0
- App Version: Nextcloud 20.0.0 | App : 2020.10.0
- Browser and Version: Firefox 81.0.2 (64 bits)
- Client OS and Version: Windows 10.0.18363.1139

**### Steps to reproduce**
I can't get the "custom fields" feature to work on any website. Here is a simple example :

**1.** I've created a web site page :

```
<HTML><BODY>
    <FORM METHOD="post">
      Server <INPUT TYPE="text" NAME="input_server" ID="input_server"><BR>
      Login <INPUT TYPE="text" NAME="input_login" ID="input_login"><BR>
      Password <INPUT TYPE="password" NAME="input_password" ID="input_password"><BR>
      <INPUT TYPE="submit" VALUE="GO">
    </FORM>
</BODY></HTML>
```

![Img01](https://user-images.githubusercontent.com/55400519/96347343-77c35080-10a1-11eb-84f9-7951d3c8a8a4.JPG)

**2.** On Nextcloud App, I've create this password entry

![Img02](https://user-images.githubusercontent.com/55400519/96347361-96c1e280-10a1-11eb-8379-9bb7180b1944.JPG)

**3.** I refresh the extension -> I connect to the created page : the new entry is detected

![Img03](https://user-images.githubusercontent.com/55400519/96347366-9de8f080-10a1-11eb-8d86-038ba61786de.JPG)

4. When I select the entry, only the login and password fields (**input_login** and **input_password**) are filled ; the **input_server** field remains empty

**### Expected result**
Custom field created in Nextcloud should be filled on the web site

**### Actual result**
Custom field remain empty
However, login and password fields are correctly filled on the web site

**### Browser log**
In Firefox: Open about:debugging#/runtime/this-firefox
sendRemoveListener on closed conduit ncpasswords@mdns.eu.274877913495 2 ConduitsChild.jsm:108

**Comment by marius-wieschollek** [comment]
Custom fields can be used to store any kind of custom data, not just extra form fields. The extension can not yet manage extra fields in login forms.

**Comment by bazalt** [comment]
An approach like [Passman Webextension](https://github.com/nextcloud/passman-webextension/wiki/Fill-any-input-with-custom-fields) would be really really great.

**Comment by flo-mic** [comment]
@marius-wieschollek what do you think about adding a type "autofill" to the password custom fields on server side? The extension could then search for an element with the name of the custom field label and place the content there. If you like this approach I would prepare a pull request for this.

**Comment by marius-wieschollek** [comment]
My original idea was to use the type `data` and a label like `ext:fields` for this. That way we can just save some JSON with the css  selectors and the data to fill. And since we will be having an edit option soon in the extension, we could extend that to make the values editable there.

**Comment by flo-mic** [comment]
Thats also a way to solve it. I think the data field is only for internal purpose but this is probably an internal use case. 

If i understand it right the new edit form should also display data items with the label prefix ext:fields and this should be passed to the client page during the fill action. 

Probably i can add this on the weekend.

**Comment by marius-wieschollek** [comment]
> I think the data field is only for internal purpose but this is probably an internal use case.

This is actually the use case i had in mind when adding the type.
