### ISSUE TITLE
Chrome extensions bug 

### ISSUE THREAD

**Issue by joomlaproffs** [marius-wieschollek/passwords-webextension#101]
The extension works great with Firefox. But in Chrome the passwords does not work directly. I need to copy username/password manually via the small icons - then it works to login. But just clicking the item just results in a "This email or username was not found." or similar message on whatever site I try to login to. Tested also by my friend with same issue. 

**Versions:**
Chrome version: Version 86.0.4240.111
NextCloud: 20.0.0
Passwords: 2020.10.0
Nextclouds Password (Chrome addon): 1.9.1

**Comment by marius-wieschollek** [comment]
Does this issue still exist with v2 of the extension?
