### ISSUE TITLE
Enable Locking of Extention

### ISSUE THREAD

**Issue by LeSnake04** [marius-wieschollek/passwords-webextension#107]
**Current Status**
The Plugin is always unlocked when launching browsers and all passwords are readable

**Feature Description**
Option to lock add-on with a pin or your Nextcloud password when starting your browser.

**Additional context**
When someone opens a browser on my PC, they have access to every of my Passwords, that is a big security Problem!
I can't suggest this add-on to someone less experienced with this  concern...

**Comment by marius-wieschollek** [comment]
See https://github.com/marius-wieschollek/passwords-webextension/issues/72 for client side encryption and master passwords

**Comment by misterbridge** [comment]
Hi, thanks that's great !
#107 points to that issue mentionning master password, but I don't see it in the options of the v2.0.0 that I have.
Will it land later after all ?
