### ISSUE TITLE
JSON Parse error with Legacy API disabled

### ISSUE THREAD

**Issue by simonspa** [marius-wieschollek/passwords-webextension#11]
Running passwords 2018.5.2 on Nextcloud 13.0.2 and trying to retrieve passwords via the web extension running in Firefox 60.0, legacy API switched off.

Login works fine, but when it tries to fetch passwords, I get a JSON parse error. Using Firefox's web extension debugger console I see

```
Encoding response failed Request { method: "GET", url: "https://cloud.server.tld/index.php…", headers: Headers, referrer: "about:client", referrerPolicy: "", mode: "cors", credentials: "omit", cache: "default", redirect: "follow", integrity: "" } SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data  background.js:1:96395
	_createRequest/</</<
```

This doesn't look very helpful to me, maybe it would be worth noting somewhere that the Legacy API has to be enabled in the app settings?

When enabling the Legacy API all works as expected.

**Comment by marius-wieschollek** [comment]
See #4 and the [admin manual](https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Administrative-Settings#user-content-enable-legacy-api)
