### ISSUE TITLE
Popup doesn't open up on latests dev version

### ISSUE THREAD

**Issue by r3pek** [marius-wieschollek/passwords-webextension#110]
### System Information
- Extension Version: 2.0.0.3706
- App Version: 2020.12.0
- Browser and Version: Brave Version 1.18.75 Chromium: 87.0.4280.101 (Official Build) (64-bit)
- Client OS and Version: Fedora 32

### Steps to reproduce
1. Click the extension icon 

### Expected result
A popup should apear with the "app menu"

### Actual result
Only a small white square apears
![image](https://user-images.githubusercontent.com/3050556/102697482-f36e8480-422d-11eb-9a11-a4ba49ff4191.png)

### Browser log
<details>
<summary>Browser log</summary>
[br_toolbar] Not Implemented: possiblyShowMenuPromo
</details>

**Comment by r3pek** [comment]
version 2.0.0.3711 fixed it

**Comment by marius-wieschollek** [comment]
:+1:
