### ISSUE TITLE
Password check results cover items

### ISSUE THREAD

**Issue by majkinetor** [marius-wieschollek/passwords-webextension#111]
With latest release I got this spam over items:

![image](https://user-images.githubusercontent.com/85767/103072054-2a91bc80-45c5-11eb-85dd-c18a8ef7d589.png)

There doesn't seem option to disable it. On testing environments we keep simple passwords because there is no need for it  to be secured and easy of access is more important.

It would be better if compromised password is just marked with icon (this entire text could go into tooltip).

The message itself doesn't have much sense - which password is compromised - I have 5 credentials there and all use the same password, yet message appears 3 times. Another solution might be to show message only once.

This also shows without any passwords sometimes:

![image](https://user-images.githubusercontent.com/85767/103072427-d63b0c80-45c5-11eb-83c8-42a26e40d139.png)

**Comment by marius-wieschollek** [comment]
I will add an option to remove the warning in the next update
