### ISSUE TITLE
Feature Request: (Auto-)clean Clipboard

### ISSUE THREAD

**Issue by sepo83** [marius-wieschollek/passwords-webextension#112]
**Current Status**
When copying a username/password it stays in  clipboard (literally :smile: ) forever, unless it is overwritten or the device is restarted.

**Feature Description**
* add a button to clean the clipboard; perhaps only if the clipboard contains a username or password from passwords-webextension
* add a "autoclean" functionality for the clipboard, that cleans the clipboard after a configurable timeout (e.g. 10s, 30s, 60s, 5m, 10m)... perhaps also do this only after a username/password was added from passwords-webextension

**Additional context**
None

**Comment by CodeAlDente** [comment]
A way to automatically clear the clipboard after n seconds would be great.

**Comment by marius-wieschollek** [comment]
There is some limitations when attempting to access the user clipboard from within the browser extension.
There is no extension api to request clipboard read access, and the general JS api is not fully implemented and uncomfortable to use for an extension.

Attempting to write to the user clipboard is usually only permitted within a user action, so there are probably some time limits in place as to how long the content can stay in the clipboard.

It also needs to be checked how we can make sure the code gets executed. The copy to clipboard code runs within the popup.
We can't do the same with the code to clear the clipboard as the code won't get executed when the popup gets closed.

**Comment by bertwesarg** [comment]
Would it be possible to have at least a button _clear clipboard_. Else I would need to select and Ctrl+C some random text in the browser. Best is to **overwrite** the content of the clipboard with noise a few times and only then clear it.

**Comment by flo-mic** [comment]
I just opened a pull request that implements this feature. So hopefully we see this soon in the official browser extension ;)
