### ISSUE TITLE
Settings result in ERR_BLOCKED_BY_CLIENT on Kiwi browser

### ISSUE THREAD

**Issue by marius-wieschollek** [marius-wieschollek/passwords-webextension#116]
### System Information
- Extension Version: 2.0.0
- App Version: 2020.12.1
- Browser and Version: Kiwi Git201105Gen347353974
- Client OS and Version: Android 10

### Steps to reproduce
1. Install the extension on kiwi
2. Clock the link to add an account manually in the first run wizard
3. Get an error: "Requests to the server have been blocked by and extension. ERR_BLOCKED_BY_CLIENT"

### Expected result
Settings open with option to create a new account

### Actual result
Kiwi blocks opening the page

**Comment by marius-wieschollek** [comment]
I am currently unable to reproduce this issue. If anyone has more information feel free to comment it here.

**Comment by scambra** [comment]
I have same issue, when I click on Open Extension Settings, it open options in incognito window, and gets this error, if I copy URL into normal window, it works
