### ISSUE TITLE
Cannot update account information after auto update

### ISSUE THREAD

**Issue by yuuichirou** [marius-wieschollek/passwords-webextension#117]
### System Information
- Extension Version: 2.0.0.0000
- Browser and Version: Chrome

After auto-update the extension is unusable. Account information cannot be updated.
After saving the account settings the extension shows an error:

>Saving failed
>The app version installed on the server is outdated.

At least in Firefox you can disable auto-updating and use the last working version.
Should be a new extension in the Chrome Web Store. It is bad desing if the application breaks after the update.

**Comment by marius-wieschollek** [comment]
Hi. would you please fill out the bug report form including the app version in use?

**Comment by yuuichirou** [comment]
From a user's point of view, I cannot find the app version, I have checked everywhere in the web view and cannot see it. I contacted the server administrator, he told me that this is version 2019.12.1.

**Comment by marius-wieschollek** [comment]
Version 2019.12.1 is really outdated by now and all versions of Nextcloud that it ever ran on are no longer supported as well. Therefore the notification is correct and your administrator should make sure to update the server. In the best case to Nextcloud 20, PHP 7.4 and Passwords 2020.12.1.

> Should be a new extension in the Chrome Web Store.

This would require every user of the extension to switch to a different extension manually and set up their account again. Given that nearly all users use a version of the app that is compatible with the extension, i think that is unjustified.
The new version enables users to use folders and tags, gives access to a more secure encryption and lays the foundation for 2FA. Having two extensions would cause a lot of confusion among users and any user attempting to use new features would either give up or end up in the forum asking for support.

> It is bad desing if the application breaks after the update.

At some point, outdated software will result in compatibility issues. I have no way of excluding some users from the update.
I would have liked to give users of an outdated app version a notification ahead of the update. But the old extension uses an old api and can't actually check the app version. And not all older versions of the app can actually provide their app version trough the api. And i personally don't believe that if someone is running an completely outdated version of Nextcloud, one more notification about the end of support would have gotten him to change that.

An upcoming release of the extension will make the notification more clear and include the minimum required version and if possible also the server version. But the only way to resolve the issue for you will be a server update. This should also be in your interest as this does not only add new features, it also brings security fixes that might be missing on your outdated server.
