### ISSUE TITLE
Move password from incognito to normal

### ISSUE THREAD

**Issue by Hacken-Dazs** [marius-wieschollek/passwords-webextension#118]
### System Information
- Extension Version: 2.0.0
- App Version: 
- Browser and Version: Firefox 84.0.1
- Client OS and Version: Windows 10

### Steps to reproduce
1.  Add a password in incognito, want to find it again to move or add it in normal folder
2. 
3. 

### Expected result
What should happen? I would find it again ....

### Actual result
What does happen? No way to find it if I don't remember the name of the entry

**Comment by marius-wieschollek** [comment]
I think a good first step for this would be to make the private folder visible in the "browse" tab when in private mode.

#27 aims to make passwords editable. So i would not include the option to move the passwords in this ticket.

**Comment by Hacken-Dazs** [comment]
Humm, sorry maybe I don't understand something, but I don't find a way to make the private folder visible ...

**Comment by marius-wieschollek** [comment]
You're right, currently you can't. I meant that i will be adding this as part of this ticket in the next feature release.

But there you can only see the passwords, not edit or move them. Currently the only way to edit a password trough the extension is to change the password and wait for the extension to detect it. Capabilities to edit passwords will be added later.

**Comment by Hacken-Dazs** [comment]
And how can I know how many pass I have in the incognito folder ?
In fact, I had a lot of them in incognito before I seen that I can't find them anymore if I don't go on the website or remember the name to search them ....

**Comment by Hacken-Dazs** [comment]
And If I found the incognito entry and add it as normal by the website, i'll have 2 times the same entry ... How to del the incognito one ?

**Comment by marius-wieschollek** [comment]
There is currently no way to do this. Private passwords only exist in private mode and are only shown in the search or the suggestions.

**Comment by Hacken-Dazs** [comment]
So, no way to delete it ...

**Comment by marius-wieschollek** [comment]
In the nightly you can now change the status of the password.
Additionally, the debug section of the addon settings contains a link to open the hidden folder in the app. There you can also edit the password and remove the status.

**Comment by Hacken-Dazs** [comment]
> 
> 
> In the nightly you can now change the status of the password.
> Additionally, the debug section of the addon settings contains a link to open the hidden folder in the app. There you can also edit the password and remove the status.

Sorry but I don't find any link to open the hidden folder. I can't change the status of the pwd too ....
I checked, I don't have any update to do, may I wait ?

**Comment by marius-wieschollek** [comment]
You likely don't use the nightly version of the extension. Here is how it works with the current stable version of the extension and the app. (extension 2.1.1 and app 2021.5.0)
![private-passwords](https://user-images.githubusercontent.com/8255857/118119024-0442b100-b3ee-11eb-81f1-ab0e72c5c764.gif)
