### ISSUE TITLE
Passlink QR-Code not working / bad usability / where to finde token?

### ISSUE THREAD

**Issue by christianalles** [marius-wieschollek/passwords-webextension#119]
### System Information
- Extension Version: 2.0.0
- App Version: 2021.1.0
- Browser and Version: chrome 87.0.4280.141
- Client OS and Version: windows 20h2

### Steps to reproduce
1. Click Passwords Chrome Webextension
2. Scan Passlink-Code and allow use of webcam
3. Open QR-Code on Phone
4. QR-Code is displayed with very bad contrast, medium gray on white. (Is this somehow being influenced by nextcloud themecolors?)
5. QR-Code is not recognizable for webcam, also scanning QR-Codes is a pain when using a notebook with an integrated webcam. This is also worse if the device showing the code has a reflective display
6. Trying to manually add user account asks for token, but leaves the user without any clues where to find this token.

### Expected result
QR-Code should be clearly high-contrast / black and white.
There should be an easy and clearly indicated way to get the token without scanning QR-Codes

### Actual result
QR-Code is not recognized
User is left clueless on how to find the token and therefore can't use the webextension anymore

**Comment by marius-wieschollek** [comment]
> QR-Code is displayed with very bad contrast, medium gray on white. (Is this somehow being influenced by nextcloud themecolors?)

Yes it uses the theme colors. I will make sure indistinguishable colors will be prevented in the next update.

> QR-Code is not recognizable for webcam, also scanning QR-Codes is a pain when using a notebook with an integrated webcam. This is also worse if the device showing the code has a reflective display

Yes, the qrcode was only intended for mobile devices. But currently the link solution only works for Firefox. I'm working on a more user friendly solution.

> Trying to manually add user account asks for token, but leaves the user without any clues where to find this token.

[Take a look at the wiki](https://github.com/marius-wieschollek/passwords-webextension/wiki/setup-manual#step-2-create-a-new-app-password).

**Comment by Numrollen** [comment]
Same here.

the config menue is somehow too big and i need to scroll to the right and down to see all options when config the user account. We use MS Edge. With QR code is horrible, i dont use smartphones for this.

**Comment by marius-wieschollek** [comment]
> the config menue is somehow too big and i need to scroll to the right and down to see all options when config the user account. We use MS Edge.

MS Edge is currently not supported. If you want MS Edge to be supported, please open a separate feature request with detailed information about the issues there.

**Comment by marius-wieschollek** [comment]
Passwords 2020.12.2 and 2021.1.1 should fix the issues you experienced server side.

Additionally, Passwords 2021.2.0 and 2.1.0 of the extension will make the QR code obsolete for your use case.
