### ISSUE TITLE
[Req] Share all Passwords of a folder

### ISSUE THREAD

**Issue by Numrollen** [marius-wieschollek/passwords-webextension#127]
**Current Status**
we have 100 data/passwords/logins centralised for the hole team. Not all services are related to personal account. we need a treestructure for this.

**Feature Description**
i would like to share all logins that are team related. 

**Additional context**
we have passwords for external sites, internal for several categorys (service accounts, accounts with other departments..)

**Comment by marius-wieschollek** [comment]
This is being planned for the Nextcloud app (https://github.com/marius-wieschollek/passwords/issues/27). I don't see currently any use for this in the webextension.
