### ISSUE TITLE
[Req] LDAP account detected as weak (duplicate)

### ISSUE THREAD

**Issue by Numrollen** [marius-wieschollek/passwords-webextension#128]
**Current Status**
I use Websites that have LDAP integrated with the same account (most of them).

**Feature Description**
Would be good to have 1 item that is my account (since Nextcloud also uses my ldap account, it could be the same). This "Account" should be useable to the prefered logins.

**Additional context**
when i change my password, i would need to change all Passwords Login that uses my ldap account.

**Comment by marius-wieschollek** [comment]
You can add additional urls as custom fields (#45) in the Nextcloud app and the extension will suggest the password on any matching website.

#87 Will eventually allow matching websites by a regular expression.

I think this should cover your use case.
