### ISSUE TITLE
"Notification for new password"-Setting not working

### ISSUE THREAD

**Issue by 9hawk8** [marius-wieschollek/passwords-webextension#129]
In the Addon-Settings for the Firefox-Addon there is an option to switch off different notifactions.
If I switch off the "Notification for new Password", this notification is still shown.

Steps to reproduce:

    1. I switch off the "Notifacation for new password" in the Addon-Settings.
    2. I am signing in on a new website with new username and password.
    3. I get notified by the Addon about a new password.

Expected result:

@ Step 3. I should not see the Notification for new password.

Actual result

@ Step 3. The Notification for new password is shown.

System Information:
- Addon Version: 2.0.0
- Passwords App Version: 2020.12.1
- Browser and Version: Firefox 84.0.2
- Client OS and Version: Win 10 20H2

But great Update on the 2.0.0 so far! Thanks for that. It looks far more modern than the previous versions and is capable of doing so much more.

**Comment by marius-wieschollek** [comment]
This should be fixed with update 2.0.1.
