### ISSUE TITLE
Can you explain more why you aren't in the chrome web store?

### ISSUE THREAD

**Issue by joewashear007** [marius-wieschollek/passwords-webextension#13]
I can;t seem to install the extension, chrome doesn't want to enable it. (And some time I have to use chrome  instead of Firefox)

![image](https://user-images.githubusercontent.com/3577785/40818462-1702c160-6525-11e8-848b-4abede05de6e.png)

**Comment by marius-wieschollek** [comment]
Publishing something on the Chrome Web Store requires a lot of bureaucracy and a verified developer account (which is even more bureaucracy and intransparent fees). I simply have not yet found the time and will to go trough that process.

**Comment by joewashear007** [comment]
Fair enough, but the extension doesn't seem to be to be installed on Chrome
without going though the Chrome web store.

Do you have any solution for that?

Thanks

**Comment by marius-wieschollek** [comment]
You can load the zip file as unpacked extension (see updated [wiki page](https://github.com/marius-wieschollek/passwords-webextension/wiki/chromium-builds)).

I will look into publishing on the Chrome Web Store in the near future.

**Comment by marius-wieschollek** [comment]
The extension is now available on the [chrome web store](https://chrome.google.com/webstore/detail/nextcloud-passwords/mhajlicjhgoofheldnmollgbgjheenbi)
