### ISSUE TITLE
Allow manually adding passwords in browser extension

### ISSUE THREAD

**Issue by drolex2** [marius-wieschollek/passwords-webextension#131]
**Current Status**
The browser extension does not provide the ability to add a password manually, That is, the user must enter a password on a website in order for it to be detected and addable. 

**Feature Description**
Not every password is for a website. I would like the ability to add any type of password via the browser extension. Please add a button for adding a password to the browser extension. The button should open another tab with an extension page that has the same password adding/editing form as in the Nextcloud Passwords app.

**Additional context**
I made a separate feature request for the ability to view/edit all password information in the extension. The work for that request and this request should be highly overlapped, because both should use essentially the same view/edit/add form on a new extension page. Here is a screenshot of the add password form from LastPass. Note that is it the same as the "Edit password" form in my other request except for the name of the form, which is "Add password" in this case.
![image](https://user-images.githubusercontent.com/7788689/104434913-b6bf5000-5583-11eb-9805-69a743acb0c0.png)

**Comment by marius-wieschollek** [comment]
The extension already offers the option to create a new password for the current tab. If you open the "collected" tab in the popup and there are no passwords, the extension shows the option to create an empty entry with just the url of the current tab. (You can delete the url and continue anyway i think.)

In https://github.com/marius-wieschollek/passwords-webextension/issues/27 there is already the edit option requested for passwords.

So i see the target in this issue to combine both functionalities to provide a full edit experience for new passwords.

**Comment by flo-mic** [comment]
@marius-wieschollek I think this one can be closed or? Also on new items you have the full edit functionalities with custom fields etc... The only side effect is the filled url field  but I think this can be managed by a user.
