### ISSUE TITLE
Password Generator Does Not Respect Settings On First Load

### ISSUE THREAD

**Issue by Prog1563** [marius-wieschollek/passwords-webextension#132]
### System Information
- Extension Version: 2.0.1.3828
- App Version: 2020.12.1
- Browser and Version: Google Chrome x64 87.0.4280.141
- Client OS and Version: Windows 10 20H2

### Steps to reproduce
1. Open the extension's popup
2. Navigate to tools
3. Wait for a password to generate

### Expected result
The generated password should respect the settings for numbers symbols and strength.

### Actual result
The generated password does not respect the settings.

### Browser log
My workplace has disabled developer options on Google Chrome.

### More details
If I click on the regenerate button after the initial password is generated, it does respect the settings provided. The same also applies if I change any of the settings because it auto regenerated when they change.

**Comment by marius-wieschollek** [comment]
This should work with 2.0.4
