### ISSUE TITLE
Stops working after trying to create a new entry with E2E-Encryption enabled

### ISSUE THREAD

**Issue by fajabird** [marius-wieschollek/passwords-webextension#133]
### System Information
- Extension Version:
- App Version:
- Browser and Version:
- Client OS and Version:

### Steps to reproduce
1. Enable E2E encryption on server
2. Install firefox addon
3. Goto plugin and let list all password entries
4. Click on "refresh"

### Expected result
Entries get refreshed and are still available

### Actual result
All entries disappear and plugin won't connect anymore to server until browser gets restarted

### Browser log
<details>
<summary></summary>

```
In Firefox:
 - Open about:debugging#/runtime/this-firefox
 - Click "Inspect" on the extension
 - Copy the content from the "Console" tab

In Chrome
 - Open chrome://extensions
 - Enable "Developer mode" in the top right corner
 - Click "Background page" on the extension
 - Copy the content from the "Console" tab
```
</details>

**Comment by marius-wieschollek** [comment]
This should be fixed with 2.0.4
