### ISSUE TITLE
Can't log out of extension to switch to a different user ID

### ISSUE THREAD

**Issue by WNYmathGuy** [marius-wieschollek/passwords-webextension#134]
### This might be a feature request as much as a "bug" report.
This extension kicks ass. On first use, after the major upgrade from the older version, this extension gives the feeling of a child opening a great birthday present.

### System Information
- Extension Version: 2.0.4
- App Version: 2021.1.2
- Browser and Version: Firefox 84.0.2 (64-bit)
- Client OS and Version: Windows 10

### Steps to reproduce
1. Attempt to sign out the current user ID with access to the browser extension

### Expected result
I should find an option to sign out of the extension.

### Actual result
I find no apparent way to sign out.

### Browser log
not applicable

**Comment by marius-wieschollek** [comment]
The extension supports multiple accounts. In the extension settings you can add any nextcloud account you have.

**Comment by WNYmathGuy** [comment]
> The extension supports multiple accounts. In the extension settings you can add any nextcloud account you have.

I'm literally turning red with embarrassment `PEBKAC`. If that feature was a snake it would have bit me. I'm so happy that you thought of everything I could want.

**Comment by WNYmathGuy** [comment]
Aw hell, @marius-wieschollek   Where do I go to `RTFM`? 
![TroubleWithAppPassword](https://user-images.githubusercontent.com/28640985/104852238-b72f5200-58c7-11eb-9114-ae0a75390bbb.png)
I can't figure out what to put into this "App Password" field. I assumed it was the password for the user ID at the URL I entered. I don't recall ever making an App Password.

**Comment by marius-wieschollek** [comment]
As you seem to be using Firefox, i would recommend [this guide](https://github.com/marius-wieschollek/passwords-webextension/wiki/setup-firefox-desktop#step-2-link-the-extension-to-your-nextcloud-account).

A [guide for the manual setup can be found here](https://github.com/marius-wieschollek/passwords-webextension/wiki/setup-manual#step-2-create-a-new-app-password).

**Comment by WNYmathGuy** [comment]
Amazing craftsmanship in the how-tos!
