### ISSUE TITLE
HTTP 429 - Too many requests

### ISSUE THREAD

**Issue by Megamezzomixer** [marius-wieschollek/passwords-webextension#136]
### System Information
- Extension Version: 2.0.4
- Browser and Version: Firefox 84.0.2
- Client OS and Version: Windows 10

### Steps to reproduce
Starting the browser and also clicking on Login

### Expected result
Synchronization and being connected

### Actual result
The "number of passwords" icon turns on, goes to 1, then disappears again. After a few retries the addon returns 429 Too many requests

### Browser Log
Addon itself:
[https://cloud.megamezzomixer.de/s/EsgLgbtTXjktMoT/preview](https://cloud.megamezzomixer.de/s/EsgLgbtTXjktMoT/preview)

Firefox:
[https://cloud.megamezzomixer.de/s/H8M33PRNSrCQW5K/preview](https://cloud.megamezzomixer.de/s/H8M33PRNSrCQW5K/preview)

**Comment by Megamezzomixer** [comment]
I can temporarily fix the problem by logging in after the problem happened and click the synchronization button multiple times.

**Comment by marius-wieschollek** [comment]
Can you check what the details of the "a is null" error in the extension log is?

**Comment by Megamezzomixer** [comment]
Yea, sure
![2021-01-26_19-05-12](https://user-images.githubusercontent.com/21281507/105885553-91155a80-6009-11eb-842d-d41b9d776815.png)

**Comment by marius-wieschollek** [comment]
I acutally meant this one: 
![grafik](https://user-images.githubusercontent.com/8255857/105887986-ad66c680-600c-11eb-8ea8-aa4a2d3827a7.png)

The "r.data is null" seems to be from a different extension
The "Could not establish connection" and "Invalid tab id" are known issues with the current version, but i don't think they are related to you.

**Comment by Megamezzomixer** [comment]
I don't really get it reconstructed. Is it saved in some kind of logfile?

**Comment by marius-wieschollek** [comment]
no, logs are discarded after the browser is closed or the extension reloaded.

If the problem still persists without the error in the logs it's probably not related.

Are you using a master password or 2FA ?

**Comment by Megamezzomixer** [comment]
No, I don't use any of that. Nor E2E.

I actually have an error when I start up the browser:
`{
  "details": {
    "data": {},
    "message": "CSE Encryption not enabled or ready",
    "file": "moz-extension://803259a7-3fd4-437d-937f-a01bf392fbdd/js/background.js",
    "line": 14,
    "stack": "Ft@moz-extension://803259a7-3fd4-437d-937f-a01bf392fbdd/js/background.js:14:146035\ngetClass@moz-extension://803259a7-3fd4-437d-937f-a01bf392fbdd/js/background.js:14:114195\ndecrypt@moz-extension://803259a7-3fd4-437d-937f-a01bf392fbdd/js/background.js:14:135606\nfromEncryptedData@moz-extension://803259a7-3fd4-437d-937f-a01bf392fbdd/js/background.js:14:121247\nmakeFolderFromApiData@moz-extension://803259a7-3fd4-437d-937f-a01bf392fbdd/js/background.js:14:141907\nmakeFromApiData@moz-extension://803259a7-3fd4-437d-937f-a01bf392fbdd/js/background.js:14:140815\n_dataToModel@moz-extension://803259a7-3fd4-437d-937f-a01bf392fbdd/js/background.js:14:116790\nfindById@moz-extension://803259a7-3fd4-437d-937f-a01bf392fbdd/js/background.js:14:116256\n",
    "time": 1611691542776
  },
  "error": {
    "name": "EncryptionNotEnabledError",
    "stack": [
      "Ft@moz-extension://803259a7-3fd4-437d-937f-a01bf392fbdd/js/background.js:14:146035",
      "getClass@moz-extension://803259a7-3fd4-437d-937f-a01bf392fbdd/js/background.js:14:114195",
      "decrypt@moz-extension://803259a7-3fd4-437d-937f-a01bf392fbdd/js/background.js:14:135606",
      "fromEncryptedData@moz-extension://803259a7-3fd4-437d-937f-a01bf392fbdd/js/background.js:14:121247",
      "makeFolderFromApiData@moz-extension://803259a7-3fd4-437d-937f-a01bf392fbdd/js/background.js:14:141907",
      "makeFromApiData@moz-extension://803259a7-3fd4-437d-937f-a01bf392fbdd/js/background.js:14:140815",
      "_dataToModel@moz-extension://803259a7-3fd4-437d-937f-a01bf392fbdd/js/background.js:14:116790",
      "findById@moz-extension://803259a7-3fd4-437d-937f-a01bf392fbdd/js/background.js:14:116256",
      ""
    ],
    "string": "EncryptionNotEnabledError: CSE Encryption not enabled or ready",
    "fileName": "moz-extension://803259a7-3fd4-437d-937f-a01bf392fbdd/js/background.js",
    "lineNumber": 14,
    "columnNumber": 146035,
    "message": "CSE Encryption not enabled or ready"
  }
}`

**Comment by marius-wieschollek** [comment]
> Starting the browser and also clicking on Login

What login button did you mean whit that?

**Comment by Megamezzomixer** [comment]
When the addon kicks me out with saying "Too many requests" I have a large blue button saying Login

**Comment by Megamezzomixer** [comment]
That "CSE Encryption not enabled or ready" error happens two times, after 10 seconds I get the Too many requests error.

**Comment by Megamezzomixer** [comment]
![2021-01-26_21-20-47](https://user-images.githubusercontent.com/21281507/105900502-6d0f4480-601c-11eb-9525-0f2e8f178a12.gif)

This is the behavior. Watch to the end, there you see it kicking me out again

**Comment by marius-wieschollek** [comment]
That is strange.
It looks like the extension crashes while trying to fetch data from the server.
The stack trace of the exception suggests that some folder is marked as using e2e.

Can you open "about:debugging#/runtime/this-firefox" and then click the "Debugging" button for the passwords extension.
Then type `browser.runtime.reload()` into the console and switch to the network tab.
There should be three "list" requests and one "show" request. None should contain "cseType":"CSEv1r1" anywhere in the response.

**Comment by Megamezzomixer** [comment]
I once had E2E, but I have used the wipe option over at the Passwords settings.

And yes, I will try doing that.

**Comment by Megamezzomixer** [comment]
![2021-01-26_21-34-52](https://user-images.githubusercontent.com/21281507/105902023-5ec22800-601e-11eb-9c8d-9d96400121c8.png)

Also I have deleted the logs before that, all this happened right after browser.runtime.reload().
I don't see any cseType in there.

**Comment by Megamezzomixer** [comment]
Thats how the request looks like: [https://cloud.megamezzomixer.de/s/K32g24rX4xk7GLH/preview](https://cloud.megamezzomixer.de/s/K32g24rX4xk7GLH/preview)

**Comment by marius-wieschollek** [comment]
![grafik](https://user-images.githubusercontent.com/8255857/105904615-a5fde800-6021-11eb-806c-1bf1496788f8.png)
I forgot that you need to open the response tab in the request details.

If you had e2e at one time, i would suggest looking into the "show" request first. If the extension was active during the reset, it might have just recreated that folder in there while still using e2e.

**Comment by Megamezzomixer** [comment]
![2021-01-26_22-03-57](https://user-images.githubusercontent.com/21281507/105905161-67b4f880-6022-11eb-90df-baf5970660a0.png)

You are right. the undesired value is present.

**Comment by Megamezzomixer** [comment]
That brings me to the question.. How do I fully disable CSE then?

**Comment by Megamezzomixer** [comment]
I have exported all my passwords, then restore default settings and finally import only my passwords. Maybe that will work.

**Comment by marius-wieschollek** [comment]
I think you should disable the extension first and then disable encryption.

You can also use the folder id shown in the request do delete the folder directly from the database.

**Comment by Megamezzomixer** [comment]
Hmm. I didn't try your approach yet, but the export & import worked apparently. I have no connection errors anymore.

**Comment by marius-wieschollek** [comment]
In theory, the reset everything command closes all sessions first and then deletes the data. I'm not really sure how the extension managed to create a folder after the reset.

But i will add a check to the validation of any new object to see if e2e is enabled when the object is e2e encrypted. That way the server might reject the item when the extension tries to save it.

**Comment by Megamezzomixer** [comment]
Maybe there still was a connection left, or inbound directly after the session closing? Not sure. Anyways. The wooden hammer method aka wiping fixed it. Thanks for your help!

**Comment by marius-wieschollek** [comment]
I will see how the extension behaves in that situation. it could also be that it opens a new session, but still uses the encryption it has from the previous session.

Thanks for reporting this.

**Comment by Megamezzomixer** [comment]
I think I know how this could have happened. I am also using the Android App "NC Passwords", maybe that interfered with the encryption.

**Comment by marius-wieschollek** [comment]
I don't think so, both android apps currently don't support encryption.
The folder in the "show" request is for the hidden passwords (which only show up in private browsing mode). You can see in the response above that the "client" which created the folder was the extension. And since the folder is also hidden, no other app can see it.
