### ISSUE TITLE
Subdomains, subdirectories, and ports

### ISSUE THREAD

**Issue by mobamoba** [marius-wieschollek/passwords-webextension#14]
Is there a way to tell the Firefox addon to distinguish between subdomains (xxx.domain.com), subdirectories (domain.com/xxx), and ports (domain.com:123)? It seems to only be looking at top level domain names and ends up giving me a huge list for domains where there are a lot of subdomains, subdirectories, and different ports for the same domain. Thanks.

**Comment by marius-wieschollek** [comment]
There is currently no way to do this. If you're looking for a specific account, you can use the search tab.

I will think about ways to support this for the next major release.

**Comment by mobamoba** [comment]
Thanks. If it helps, Passman does this (though I think the developer has stopped developing it) and maybe there's some reuseable code in there?
