### ISSUE TITLE
Missing extension icon in Chromium

### ISSUE THREAD

**Issue by sausix** [marius-wieschollek/passwords-webextension#142]
Could not find any related bug reports or F.A.Q. entries about this issue.

### System Information
- Extension Version: 2.0.4
- App Version: 2021.1.2
- Browser and Version: Chromium Version 88.0.4324.96 (Official Build)
- Client OS and Version: Arch Linux (64-Bit)

### Steps to reproduce
- Install web extension
- Configure and connect

### Expected result
Extension icon should be visible.

### Actual result
No icon, so I can use the extension only by context menu
![pbug](https://user-images.githubusercontent.com/21084645/107154385-fc005300-6972-11eb-91b7-00acb7838d9d.png)

### Browser log
Console.log of background page is empty.
I will restart the browser and add information if available.

**Comment by marius-wieschollek** [comment]
![grafik](https://user-images.githubusercontent.com/8255857/107155953-cca21400-697b-11eb-935c-436fbc13b49c.png)
Have you checked here?

**Comment by sausix** [comment]
Damn.... Never used that dialog.
I'm ashamed.

Other extensions always were visible immediately.

Thank you for the hint!
