### ISSUE TITLE
"This account is deactivated" 

### ISSUE THREAD

**Issue by aronmal** [marius-wieschollek/passwords-webextension#143]
### System Information
- Extension Version: 2.0.4.3887
- App Version: 2020.12.2	
- Browser and Version: Chrome 88.0.4324.146
- Client OS and Version: Windows 10 64-bit

### Steps to reproduce
1. enable two Factor authentication for NC account
2. create apps password and use it in the extension setting to login
3. then it immediately works, but after some time (I guess when i shut down my PC) i have to login in again and it is showing "This account is deactivated" in the extension settings. I don't use my passwords currently not that often because i am normally staying logged in, but when i want to use the extension I always have to login again.

### Expected result
Stay logged in/account activated

### Actual result
it is showing "This account is deactivated" in the extension settings

### Browser log
<details>
<summary>Browser log</summary>

background.js:1 undefined Object Object "Error
    at Object._getDetailsFromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:6349)
    at Object._addError (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:5708)
    at Object.logError (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:5543)
    at Object._sendMessage (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:11529)"
_addError @ background.js:1
background.js:1 Uncaught (in promise) Object
next.malcher-noh.de/index.php/apps/passwords/api/1.0/settings/get:1 Failed to load resource: the server responded with a status of 401 ()
background.js:1 HTTP 401 - Unauthorized UnauthorizedError: HTTP 401 - Unauthorized
    at Vt.getClass (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:123920)
    at Lt.getClass (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:163091)
    at et._getHttpError (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:139450)
    at et._processJsonResponse (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:138879)
    at et.send (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:137416)
    at async m.findByName (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:127742)
    at async Object._getServerSetting (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:28:226850)
    at async Object._serverGet (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:28:226145)
    at async Object.get (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:28:225131)
    at async Object.get (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:92490) Object UnauthorizedError: HTTP 401 - Unauthorized
    at Vt.getClass (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:123920)
    at Lt.getClass (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:163091)
    at et._getHttpError (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:139450)
    at et._processJsonResponse (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:138879)
    at et.send (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:137416)
    at async m.findByName (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:127742)
    at async Object._getServerSetting (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:28:226850)
    at async Object._serverGet (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:28:226145)
    at async Object.get (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:28:225131)
    at async Object.get (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:92490)
_addError @ background.js:1
next.malcher-noh.de/index.php/apps/passwords/api/1.0/settings/get:1 Failed to load resource: the server responded with a status of 401 ()
next.malcher-noh.de/index.php/apps/passwords/api/1.0/settings/get:1 Failed to load resource: the server responded with a status of 401 ()
next.malcher-noh.de/index.php/apps/passwords/api/1.0/settings/get:1 Failed to load resource: the server responded with a status of 401 ()
next.malcher-noh.de/index.php/apps/passwords/api/1.0/settings/get:1 Failed to load resource: the server responded with a status of 401 ()
next.malcher-noh.de/index.php/apps/passwords/api/1.0/settings/get:1 Failed to load resource: the server responded with a status of 401 ()
next.malcher-noh.de/index.php/apps/passwords/api/1.0/settings/get:1 Failed to load resource: the server responded with a status of 401 ()
next.malcher-noh.de/index.php/apps/passwords/api/1.0/settings/get:1 Failed to load resource: the server responded with a status of 401 ()
next.malcher-noh.de/index.php/apps/passwords/api/1.0/settings/get:1 Failed to load resource: the server responded with a status of 401 ()
next.malcher-noh.de/index.php/apps/passwords/api/1.0/settings/get:1 Failed to load resource: the server responded with a status of 401 ()
next.malcher-noh.de/index.php/apps/passwords/api/1.0/settings/get:1 Failed to load resource: the server responded with a status of 401 ()
next.malcher-noh.de/index.php/apps/passwords/api/1.0/settings/get:1 Failed to load resource: the server responded with a status of 401 ()
next.malcher-noh.de/index.php/apps/passwords/api/1.0/settings/get:1 Failed to load resource: the server responded with a status of 401 ()

</details>

### Personal Information
I tryed finding a semilar problem in the issiues, but i only found solution apps passwords. But i also found feature request for an autologout or somthink (#33 and #69) I don't know if there is a connection with my problem, it is only an assumption.

**Comment by marius-wieschollek** [comment]
does the app password still exist if this happens?

**Comment by aronmal** [comment]
Yes, and i can use it again to login. At the first time i created a new one, but both app passwords work

**Comment by aronmal** [comment]
I now closed and open Chrome, still functioning, I restarted my computer, also functioning. I don't know why or when it happen, but i will try to have an eye on how long it will work.

**Comment by aronmal** [comment]
I checked it today, and it is again deactivated. So it does not work longer than a day. I don't know if it is important, but i unplug my computer from electricity over night with a wlan relay. Maybe the Computer clock or something is stopping and I read (like in my first post mentioned) that you added a auto logout timer? I hope i am not on the wrong way.

**Comment by marius-wieschollek** [comment]
> I don't know if it is important, but i unplug my computer from electricity over night with a wlan relay.

I don't think so. Unless you PC is running while you unplug it, the data should be saved.

> I read (like in my first post mentioned) that you added a auto logout timer?

This feature is on track for 2.1.0, so it should not be part of the 2.0.4 source code. Additionally this feature just forgets the master password. The login data for the server is still there.

I think it could be that the extension somehow looses the app password. Maybe next time this happens you can try the following:
Open `chrome://extensions`, enable the developer mode in the top right and the click on the "background page" link by the extension. Then run `chrome.storage.sync.get('servers', console.log)` from the console. Make sure that you have all log levels enabled so you see the output. The result should be an object with the property servers which contains a JSON string. The app password should be in there as "token".

**Comment by aronmal** [comment]
Yes, there is Token, but it is neither the first nor the second app password I created. But I think it could be the old app password from my old nextcloud instance. So it makes sense to not work.

Console output:
`servers: "[{"baseUrl":"https://DOMAIN/","user":"USERNAME","token":"TOKEN","id":"b95b14fc-df18-408b-ae8c-022078543dc4","label":"Nextcloud Konto","enabled":false,"rootFolder":"00000000-0000-0000-0000-000000000000","inboxFolder":null,"privateFolder":"494ca1b7-2e00-410b-ab7b-09cfeaec43ae","inboxTag":null}]"`

**Comment by aronmal** [comment]
I have now again changed the extension settings with the correct app password and it is now the right one.

`servers: "[{"baseUrl":"https://DOMAIN/","user":"USERNAME","token":"CORRECT-TOKEN","id":"b95b14fc-df18-408b-ae8c-022078543dc4","label":"Nextcloud Konto","enabled":true,"rootFolder":"00000000-0000-0000-0000-000000000000","inboxFolder":null,"privateFolder":"905a9fb2-897b-4c41-bfec-e57814eef17c","inboxTag":null}]"`

**Comment by aronmal** [comment]
But I don't know what the trigger for it to be changed is.

**Comment by aronmal** [comment]
Hey, I recently removed the 2FA via Command Line (OCC) because my phone is being repaired. When I did this i logged in on my Laptop with the app password and it worked, but not for too long. Now (a little later) I tried logging in at my PC and one of the two app passwords does not work completely and the second didn't worked at the first and second try, it said something like no connection possible after it showed successfully saved and now i was able to login/connect. Lets see how long it will stay like that.

**Comment by aronmal** [comment]
Something new? I still have the problem on my computer and laptop. I guess you cant recreate the problem, because you don't answer.

**Comment by marius-wieschollek** [comment]
Sorry, i lost track of the issue.

I can't reproduce the issue so far, but i think it could be an issue with the browser synchronization. (If you use that)
Currently the extension leaves deciding which data is new or old completely to the browser and just reloads the servers after a sync event happened. It then logs `Reloaded servers after browser sync` to the browser log.
I could imagine that somehow old data gets synchronized over new data or something alike.

**Comment by aronmal** [comment]
Hello, I wanted to let you know that the problem is solved. It was the account synchronization. I turned it off for extensions on my PC and Laptop and since then it is working.

Where to find:
In the Settings, Synchronization, Manage what to sync and then turn of extension.
