### ISSUE TITLE
App recognizes passwords thrice

### ISSUE THREAD

**Issue by Burschi500** [marius-wieschollek/passwords-webextension#146]
### System Information
- Extension Version: 2.1.0
- App Version: 2021.2.0
- Browser and Version: Firefox 85.0.1 (64-Bit)
**OS:**
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=groovy
DISTRIB_DESCRIPTION="Ubuntu 20.10"
NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy

```

### Steps to reproduce
1. When the app recognizes a new usr/pw combination i get three pop-ups for newly recognized pw 

### Expected result
Only one pop-up should ...errr... pop up

### Actual result
Three pop-ups and entries into suggestions

### Nextcloud log
No error or anything in NC log

</details>

**Comment by MrHighVoltage** [comment]
I can reproduce this exact behavior on Firefox 85.0.2 64bit on Arch Linux.
It happend while registering on Gitlab.

**Comment by flo-mic** [comment]
I'm facing the same issue. I will have a look on this issue when #151 is merged. I need to touch this function anyway as soon as password recommendations are possible on domain level to avoid storing same credentials for different subdomains.
