### ISSUE TITLE
Edit Existing Credentials. 

### ISSUE THREAD

**Issue by RJ-Make** [marius-wieschollek/passwords-webextension#149]
**Feature Description**
Add another option in the screen shot below to allow for credentials to be edit. 

**Additional context**
<img width="277" alt="2021-02-17_17-53-51" src="https://user-images.githubusercontent.com/8496835/108278536-2c9d7500-7149-11eb-951d-f0fec9653d59.png">

**Comment by thomasesr** [comment]
Yes! this is a must have for when you change some website's password. Without it I have to navigate to my nextcloud website and change it manually. And with almost 1000 passwords it gets tedious to load and search it to change it from there, this would be a real time saver.
