### ISSUE TITLE
It closes without allowing to enter a password

### ISSUE THREAD

**Issue by camammoli** [marius-wieschollek/passwords-webextension#15]
I have it installed in Firefox 60.0.1 (64-bits) and, when configuring, it closes when I select the password field, without giving me time to enter anything

**Comment by marius-wieschollek** [comment]
This is a [firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1461591)

you can check out this [special alpha build](https://github.com/marius-wieschollek/passwords/files/2063190/passwords-webextension-1.5.1c.zip) by unzipping the file and loading it from the about:debugging page.

**Comment by camammoli** [comment]
That worked. Thank you

**Comment by marius-wieschollek** [comment]
Well then i will release this as regular firefox version soon.

**Comment by marius-wieschollek** [comment]
The version 1.5.1c with this workaround is now available on AMO: https://addons.mozilla.org/de/firefox/addon/nextcloud-passwords/

**Comment by camammoli** [comment]
Thanks again. I just tried it and it works great!
