### ISSUE TITLE
Feature request: password filling for browser basic authentication dialogs

### ISSUE THREAD

**Issue by barcoboy** [marius-wieschollek/passwords-webextension#150]
Not sure if this is possible, but if so, I'd like to see this added to the browser extensions.

Right now, when a website presents a basic authentication dialog, it is impossible to use the browser extensions to fill out the dialog box.  If a valid password entry is on the server, using Firefox, the extension in the Suggestions tab displays "Did not find any related passwords", and you have to click on the Browse tab to copy and paste the username and password to the dialog.  Using Chrome, the password to the site is found in the Suggestions tab, but clicking on it doesn't paste it to the dialog... again a copy/paste has to be manually done.

This isn't a huge problem, but it would be a nice feature to have available.

![PassDialog](https://user-images.githubusercontent.com/6472190/108414571-667a8400-71fa-11eb-970b-025840dc59bf.jpg)

**Comment by marius-wieschollek** [comment]
have you checked the http basic auth option in the extension settings?
With that the extension will autofill the first suggestion if a basic auth request comes.

**Comment by barcoboy** [comment]
Thank you, I was not aware of that option.  That works, and will save me some time.

But could the option to manually auto-fill the dialog be kept open as a new feature request?  I know it sounds dumb to "manually auto" a process, but I'd prefer to maintain control of when I do the paste myself.  If you don't want to implement this at some point, I'd totally understand though.

**Comment by marius-wieschollek** [comment]
No, we're limited by the browser api here. The extension gets the event from the browser api and has to return the credentials which are sent to the server. Only if we don't do anything you get the ui - without data obviously.

**Comment by barcoboy** [comment]
Ah OK, makes sense... thanks for the explanation.
