### ISSUE TITLE
Interface covered with errors

### ISSUE THREAD

**Issue by toxn** [marius-wieschollek/passwords-webextension#153]
### System Information
- Extension Version: 2.1.0
- App Version:
- Browser and Version: Chromium (Any), Firefox (Any)
- Client OS and Version: Gnu/Linux based

For a reason I have not yet inspected, I get an error for each connection to my private nextcloud server.
The result is that the interface is covored permanently with errors, which must be removed one by one
![Screenshot_20210222_090033](https://user-images.githubusercontent.com/376495/108679630-1f87d980-74ed-11eb-9e5c-b90926ec5559.png)

A quick answer to two address this issue could be to
- limit number of displayed errors,
- not display errors over interface,
- display an error type only one time (in my case, all errors are the same type),
- add a button to dismiss all errors in one click,
- replace errors banners by a single (discreet) error warning sign that would open an error browsing view,
- display errors in a dedicated tab.

**Comment by marius-wieschollek** [comment]
See #139

**Comment by toxn** [comment]
My problem is not the error, wich I will correct (being the admin of my nextcloud server), but the fact that multiple errors render the plugin somehow cumbersome to use.
