### ISSUE TITLE
Found invalid custom field error

### ISSUE THREAD

**Issue by marius-wieschollek** [marius-wieschollek/passwords-webextension#154]
### System Information
- Extension Version: 2.1.0
- App Version: 2021.2.0
- Browser and Version: Firefox & Chrome
- Client OS and Version: any

### Steps to reproduce
1. Start the browser
2. Open the extension popup
3. See the error message "Found invalid custom field error"

### Expected result
No error message.

### Actual result
Error message appears

If you have this error, please copy and post the error details below. Make sure to remove any private data from the result as the error details likely contain the data from the affected custom field.

**Comment by Oberlurch3000** [comment]
Since the last update I've the same problem. I'm having about 10 to 20 error messages of this kind. You have to click them all away to be able to copy the password. Pretty annoying... My Nextcloud is running on a Raspi 4.

**Comment by marius-wieschollek** [comment]
@Oberlurch3000 Can you open the extension settings and then copy the the error details from the debug tab? Just make sure to remove any private data if there is any. The error details should include the invalid custom field.

**Comment by Oberlurch3000** [comment]
This is error nr. 1 that appears several times:

{
  "details": {
    "data": {},
    "message": "s is not iterable",
    "stack": "TypeError: s is not iterable\n    at A._createIndex (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:28149)\n    at A.indexItem (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:27593)\n    at Object.addItem (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:30269)\n    at Object.addItems (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:30103)\n    at Object._reloadRepository (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:28:225419)\n    at async Promise.all (index 0)\n    at async Object._reloadServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:28:224869)",
    "time": 1616942193231
  },
  "error": {
    "name": "TypeError",
    "stack": "TypeError: s is not iterable\n    at A._createIndex (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:28149)\n    at A.indexItem (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:27593)\n    at Object.addItem (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:30269)\n    at Object.addItems (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:30103)\n    at Object._reloadRepository (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:28:225419)\n    at async Promise.all (index 0)\n    at async Object._reloadServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:28:224869)",
    "string": "TypeError: s is not iterable",
    "message": "s is not iterable"
  }
}

**Comment by Oberlurch3000** [comment]
This is nr. 2:
{
  "details": {
    "data": {
      "_client": {
        "baseUrl": "https://mydomain.de/",
        "user": "myuser",
        "token": "mytoken",
        "id": "56fb11bd-f64b-4499-a8f9-b3ba3ed23841",
        "label": "Nextcloud Konto",
        "enabled": true,
        "lockable": false,
        "rootFolder": "00000000-0000-0000-0000-000000000000",
        "inboxFolder": null,
        "privateFolder": "0359a292-144d-4504-ad64-c933f236f60d",
        "timeout": 0,
        "inboxTag": null
      }
    },
    "message": "Client Nextcloud Konto is not authorized",
    "stack": "ClientNotAuthorizedError: Client Nextcloud Konto is not authorized\n    at h.getHiddenFolder (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:24:303515)\n    at Object._loadHiddenPasswords (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:28:225485)\n    at Object._reloadServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:28:225005)",
    "time": 1616942695406
  },
  "error": {
    "name": "ClientNotAuthorizedError",
    "stack": "ClientNotAuthorizedError: Client Nextcloud Konto is not authorized\n    at h.getHiddenFolder (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:24:303515)\n    at Object._loadHiddenPasswords (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:28:225485)\n    at Object._reloadServer (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:28:225005)",
    "string": "ClientNotAuthorizedError: Client Nextcloud Konto is not authorized",
    "message": "Client Nextcloud Konto is not authorized",
    "_client": {
      "baseUrl": "https://mydomain.de/",
      "user": "myuser",
      "token": "mytoken",
      "id": "56fb11bd-f64b-4499-a8f9-b3ba3ed23841",
      "label": "Nextcloud Konto",
      "enabled": true,
      "lockable": false,
      "rootFolder": "00000000-0000-0000-0000-000000000000",
      "inboxFolder": null,
      "privateFolder": "0359a292-144d-4504-ad64-c933f236f60d",
      "timeout": 0,
      "inboxTag": null
    }
  }
}

**Comment by Oberlurch3000** [comment]
And this is Nr. 3:
{
  "details": {
    "data": {
      "field": {},
      "level": "error"
    },
    "message": "Found invalid custom field",
    "stack": "Error: Found invalid custom field\n    at Object.error (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:5294)\n    at S.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:140599)\n    at S.fromJSON (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:140471)\n    at M.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:139393)\n    at M.fromEncryptedData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:138365)\n    at kt.makePasswordFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:158325)\n    at kt.makeFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:157938)\n    at g._dataToModel (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:133771)\n    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:133632\n    at new Promise (<anonymous>)",
    "time": 1616948993428
  },
  "error": {
    "name": "Error",
    "stack": "Error: Found invalid custom field\n    at Object.error (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:5294)\n    at S.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:140599)\n    at S.fromJSON (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:140471)\n    at M.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:139393)\n    at M.fromEncryptedData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:138365)\n    at kt.makePasswordFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:158325)\n    at kt.makeFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:157938)\n    at g._dataToModel (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:133771)\n    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:133632\n    at new Promise (<anonymous>)",
    "string": "Error: Found invalid custom field",
    "message": "Found invalid custom field"
  }
}

**Comment by Oberlurch3000** [comment]
> @Oberlurch3000 Can you open the extension settings and then copy the the error details from the debug tab? Just make sure to remove any private data if there is any. The error details should include the invalid custom field.

{
"details": {
"data": {
"field": {},
"level": "error"
},
"message": "Found invalid custom field",
"stack": "Error: Found invalid custom field\n at Object.error (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:5294)\n at S.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:140599)\n at S.fromJSON (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:140471)\n at M.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:139393)\n at M.fromEncryptedData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:138365)\n at kt.makePasswordFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:158325)\n at kt.makeFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:157938)\n at g._dataToModel (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:133771)\n at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:133632\n at new Promise ()",
"time": 1616948993428
},
"error": {
"name": "Error",
"stack": "Error: Found invalid custom field\n at Object.error (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:5294)\n at S.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:140599)\n at S.fromJSON (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:140471)\n at M.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:139393)\n at M.fromEncryptedData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:138365)\n at kt.makePasswordFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:158325)\n at kt.makeFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:157938)\n at g._dataToModel (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:133771)\n at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:133632\n at new Promise ()",
"string": "Error: Found invalid custom field",
"message": "Found invalid custom field"
}
}

**Comment by Oberlurch3000** [comment]
@marius-wieschollek this is the debug information.

{
"details": {
"data": {
"field": {},
"level": "error"
},
"message": "Found invalid custom field",
"stack": "Error: Found invalid custom field\n at Object.error (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:5294)\n at S.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:140599)\n at S.fromJSON (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:140471)\n at M.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:139393)\n at M.fromEncryptedData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:138365)\n at kt.makePasswordFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:158325)\n at kt.makeFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:157938)\n at g._dataToModel (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:133771)\n at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:133632\n at new Promise ()",
"time": 1616948993428
},
"error": {
"name": "Error",
"stack": "Error: Found invalid custom field\n at Object.error (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:5294)\n at S.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:140599)\n at S.fromJSON (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:140471)\n at M.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:139393)\n at M.fromEncryptedData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:138365)\n at kt.makePasswordFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:158325)\n at kt.makeFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:157938)\n at g._dataToModel (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:133771)\n at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:133632\n at new Promise ()",
"string": "Error: Found invalid custom field",
"message": "Found invalid custom field"
}
}

**Comment by Oberlurch3000** [comment]
Solved it by exporting all passwords and importing them while overwriting all existing ones.
