### ISSUE TITLE
how to save passwords ?

### ISSUE THREAD

**Issue by PhieF** [marius-wieschollek/passwords-webextension#16]
Hi :)

On gnome-shell when entering a web site with a password, I've got a notification asking me whether I want to save the password but there are no button to say "yes" and clicking the notification isn't enough, Am I missing something ? 

Thanks ! :)

**Comment by marius-wieschollek** [comment]
Usually clicking the notification is enough. I tested this on a blank Ubuntu 18.04.
![save-password](https://user-images.githubusercontent.com/8255857/41510421-99ce0478-7264-11e8-87fc-6b4a0639f2b5.gif)

**Comment by marius-wieschollek** [comment]
Closed because no reply was given
