### ISSUE TITLE
Extension floods NC logs with errors

### ISSUE THREAD

**Issue by grondinm** [marius-wieschollek/passwords-webextension#165]
### System Information
- Extension Version: 2.2.0.4057
- App Version: 2021.3.0 (Nextcloud 21)
- Browser and Version: FireFox 86.0.1
- Client OS and Version: Running Gentoo linux

After upgrading to NextCloud 21 I was looking at my logs(as i had had issues with the upgrade). The last remaining error entries seem to point to this extension.

In the NC log this error just repeats every few minutes

Raw error
https://paste.marcg.pizza/~marcg/ca30e8c027dbcc103ffa52c1e007e2293e09c531

Formatted Error
https://paste.marcg.pizza/~marcg/4e80f9077f5ed56f8797de5c1c2f43351943b366

I only suspect this extension(and not the password app) because of the mentioned User Agent in the error.

Let me know if you need any other details or if you want the errors pasted here.

Thank you

**Comment by marius-wieschollek** [comment]
That does not look like an issue in the Passwords app or the webextension.
The stack trace contains no call to a method or class from the app. It's all just NC core code.

Seems like this issue to me: https://github.com/nextcloud/server/issues/25807

**Comment by grondinm** [comment]
Hey,

Thank you for the quick reply. I did have a quick look at the NC issues before submitting this. Somehow i missed that.

Guess i was already focused on this extension/app since it seems to be the only thing to trigger this error.

Hopefully NC team addresses shortly.

Thank you for the extension.

I'll close this for now and see what happens on the NC side.
