### ISSUE TITLE
Passwords are not saved to nextcloud server

### ISSUE THREAD

**Issue by srednax** [marius-wieschollek/passwords-webextension#169]
### System Information
- Extension Version:2.1.1
- App Version:latest stable
- Browser and Version:firefox linux latest stable
- Client OS and Version:archlinux fully up to date

### Steps to reproduce
1. It's really a fight to learn how to use this, but I did get it to save a password, and I could search for it and get it pasted into the website. However, it is not written back to my nextcloud server, not even when  clicking the update button. And it saved it into an unwanted folder named "Private passwords". I did NOT create that one or ask for it. 
2. 
3. 

### Expected result
What should happen? I expexct my passwords created in firefox to be saved to my nextcloud account.

### Actual result
What does happen? nothing, really

### Browser log
<details>
<summary>Browser log</summary>

```
In Firefox:
 - Open about:debugging#/runtime/this-firefox <-- THIS IS BLANK
 - Click "Inspect" on the extension
 - Copy the content from the "Console" tab

In Chrome
 - Open chrome://extensions
 - Enable "Developer mode" in the top right corner
 - Click "Background page" on the extension
 - Copy the content from the "Console" tab
```
</details>

**Comment by marius-wieschollek** [comment]
If a new password is detected, there is a switch for the option "hidden password". If you're browsing in private mode, that is enabled by default. Hidden passwords don't appear in the passwords app, but they are saved in Nextcloud.

**Comment by srednax** [comment]
You need documentation and an easier to understand ui. And how do I turn this 
misfeature off entirely?

mandag den 5. april 2021 10.42.48 CEST skrev M. Wieschollek:
> If a new password is detected, there is a switch for the option "hidden
> password". If you're browsing in private mode, that is enabled by default.
> Hidden passwords don't appear in the passwords app, but they are saved in
> Nextcloud.

**Comment by srednax** [comment]
This is horrendous!

The "hidden" switch is not even visible when presented with a password.
There is no way to manage your hidden passwords, making them a burden.

Btw, when the extension says "new passwords detected, click the icon to save", one first have to search for that new item. It is not possible from the UI to figure out where they are. Horrible UI design - again!

You don't sync with the nextcloud server when a password is saved or changed, as far as I can see. If you do you do not tell me.

You don't consider updating passwords, as far as I can see. If you do, you do not tell me.

All in all, while saving passwords to nextcloud creates value, your addon is a problem.

**Comment by marius-wieschollek** [comment]
> The "hidden" switch is not even visible when presented with a password.

The switch is right at the end of the form: 
![grafik](https://user-images.githubusercontent.com/8255857/117535027-2bffd680-aff4-11eb-9489-08989c90ad28.png)

>  There is no way to manage your hidden passwords, making them a burden.

There are actually several ways. The easiest one is to update to the nightly version where passwords can be edited.
The other one is to go into the extension settings, copy the hidden folder id in the debug settings and then go to the Nc app and put '/' + the id behind /folders in the url in the folders section. There you can see the passwords and with the current version of the app you can edit them and uncheck the "hidden password" field and save it (and move it to another folder)

> Btw, when the extension says "new passwords detected, click the icon to save", one first have to search for that new item. It is not possible from the UI to figure out where they are. Horrible UI design - again!
 
Clicking on the notification does is not considered a "user interaction" by the browser. Therefore it is not possible to open the popup automatically after this. 

> You don't sync with the nextcloud server when a password is saved or changed, as far as I can see. If you do you do not tell me.

I don't understand what you're saying. When you click save in the collected tab, the password is saved to NC. Passwords aren't saved anywhere else. The extension itself fetches all data from the server every 15 minutes. I'm pretty sure users would be annoyed if the extension told them every time.

> You don't consider updating passwords, as far as I can see. If you do, you do not tell me.

Both the extension and the app offer a nightly version. If you do want to see what is being worked on, check them out.

> All in all, while saving passwords to nextcloud creates value, your addon is a problem.

Well, then write your own or use another client. Or make a PR with useful changes for this issue.

**Comment by srednax** [comment]
Hi,
Thanks for answering :)

lørdag den 8. maj 2021 12.10.47 CEST skrev M. Wieschollek:
> > The "hidden" switch is not even visible when presented with a password.
> 
> The switch is right at the end of the form:
> ![grafik](https://user-images.githubusercontent.com/8255857/117535027-2bffd6
> 80-aff4-11eb-9489-08989c90ad28.png)

I found it because you claimed it was there. I think it should be visible to 
the user instead of hidden, since otherwise there is no obvious way to know 
it's there.

> >  There is no way to manage your hidden passwords, making them a burden.
> 
> There are actually several ways. The easiest one is to update to the nightly
> version where passwords can be edited. The other one is to go into the
> extension settings, copy the hidden folder id in the debug settings and
> then go to the Nc app and put '/' + the id behind /folders in the url in
> the folders section. There you can see the passwords and with the current
> version of the app you can edit them and uncheck the "hidden password"
> field and save it (and move it to another folder)

Well, thank you, but neither of those are user friendly. I'll look forward to 
it being part of the ui,

> > Btw, when the extension says "new passwords detected, click the icon to
> > save", one first have to search for that new item. It is not possible
> > from the UI to figure out where they are. Horrible UI design - again!
> Clicking on the notification does is not considered a "user interaction" by
> the browser. Therefore it is not possible to open the popup automatically
> after this.

Maybe when a new password is detected, it could be in the front automatically. 
You detect it, so you could put the relevant ui page in front. The current way 
is quite confusing.

> > You don't sync with the nextcloud server when a password is saved or
> > changed, as far as I can see. If you do you do not tell me.
> I don't understand what you're saying. When you click save in the collected
> tab, the password is saved to NC. Passwords aren't saved anywhere else. The
> extension itself fetches all data from the server every 15 minutes. I'm
> pretty sure users would be annoyed if the extension told them every time.

Ok, that sounds right.
My issue is that I can't save a password in the extension, and then find it in 
the app on my phone or on the web nextcloud interface, but I'll have to test 
that some more then.

I can see the problem with messaging about. updating from the server. Maybe an 
emblem on the icon in case new passwords were detected?

> > You don't consider updating passwords, as far as I can see. If you do, you
> > do not tell me.
> Both the extension and the app offer a nightly version. If you do want to
> see what is being worked on, check them out.

I'm unlikely to, but good to know that it's being developed :)

> > All in all, while saving passwords to nextcloud creates value, your addon
> > is a problem.
> Well, then write your own or use another client. Or make a PR with useful
> changes for this issue.

I do not know what a "PR" is. Feature request? 

Kindly,
Anders

**Comment by marius-wieschollek** [comment]
> I found it because you claimed it was there. I think it should be visible to
the user instead of hidden, since otherwise there is no obvious way to know
it's there.

I've added a change to the nightly that pushes the setting right to the top in the new password form when it's enabled.

> Well, thank you, but neither of those are user friendly. I'll look forward to
it being part of the ui

I meant this as a workaround for you, if you have passwords that you want to move from hidden to "normal".

> Maybe when a new password is detected, it could be in the front automatically.
You detect it, so you could put the relevant ui page in front. The current way
is quite confusing.

I checked this. If you click the notification, it actually does that. It's just on Firefox where it can't open the popup, on Chromium it works fine. So this is more a browser specific limitation.

> I do not know what a "PR" is. Feature request?

PR as in "Pull Request". This is open source software, so you're free to fork it, change it and make a PR.

**Comment by error420** [comment]
This took me a few reads to figure out so here is a quick way to reveal a missing password if accidentally saved as private:
1. Right click on the extension (lock icon in upper right in Google Chrome browser).
2. Select "Manage extension"
3. Select "Allow in Incognito"
4. Open new incognito window and log into the newly-available passwords icon in upper right as you normally would.
5. Click the Browse icon in the passwords extension and select "Private Passwords".
6. Select each private password and then edit to toggle/disable private mode. 
7. Don't forget to sync to save changes back to server.
