### ISSUE TITLE
This account is deactivated. It will be activated after it was saved successfully.

### ISSUE THREAD

**Issue by Vinceg76** [marius-wieschollek/passwords-webextension#171]
Hi, 

Everytime I restart my computer, the password plugin is deactivated.
I use TOTP on the nextcloud instance and I have to create a new app password every day to reconnect the plugin.
It is pretty annoying...

If you need more information, please tell me.

Thank you in advance, 

Vincent

**Comment by marius-wieschollek** [comment]
Could it be this issue: https://github.com/marius-wieschollek/passwords-webextension/issues/143

**Comment by Vinceg76** [comment]
I didn't see it, I'll close the issue and continue on the other thread if it doesn't work.
Thanks
