### ISSUE TITLE
Edge extension settings screen not responsive (scrollbars)

### ISSUE THREAD

**Issue by GrumpyMeow** [marius-wieschollek/passwords-webextension#173]
### System Information
- Extension Version:
- App Version: 2.1.0
- Browser and Version: v89.0.774.77 (Official build) (64-bits)
- Client OS and Version:  Windows 10 

### Steps to reproduce
1. Install the Edge browser extension

### Expected result
I expect to see a screen where i can easily enter the Nextcloud connection-settings

### Actual result
I don't see all controls of the window and have to use the scrollbars to see essential buttons and fields.

### Suggestion
Removal of these styles already improves the user-experience:
* body.options: width: 800px
* body: height: 800px
It's probably a good idea to make the screen "responsive" as apparently the browser doesn't open the window at the expected size (anymore).

**Comment by marius-wieschollek** [comment]
Should be fixed with 2.1.2
