### ISSUE TITLE
Always "Found invalid custom field error"

### ISSUE THREAD

**Issue by Oberlurch3000** [marius-wieschollek/passwords-webextension#175]
Since a few updates ago I always get several error messages in the chrome or firefox web extension.
I don't know how the debug report could help me finding the cause of this error. What can I do about this?

I don't use any custom fields beside the standard fields: Name, Link, User, Password

{
  "details": {
    "data": {
      "field": {},
      "level": "error"
    },
    "message": "Found invalid custom field",
    "stack": "Error: Found invalid custom field\n    at Object.error (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:5294)\n    at S.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:140599)\n    at S.fromJSON (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:140471)\n    at M.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:139393)\n    at M.fromEncryptedData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:138365)\n    at kt.makePasswordFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:158325)\n    at kt.makeFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:157938)\n    at g._dataToModel (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:133771)\n    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:133632\n    at new Promise (<anonymous>)",
    "time": 1621167464415
  },
  "error": {
    "name": "Error",
    "stack": "Error: Found invalid custom field\n    at Object.error (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:1:5294)\n    at S.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:140599)\n    at S.fromJSON (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:140471)\n    at M.fromObject (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:139393)\n    at M.fromEncryptedData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:138365)\n    at kt.makePasswordFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:158325)\n    at kt.makeFromApiData (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:157938)\n    at g._dataToModel (chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:133771)\n    at chrome-extension://mhajlicjhgoofheldnmollgbgjheenbi/js/background.js:22:133632\n    at new Promise (<anonymous>)",
    "string": "Error: Found invalid custom field",
    "message": "Found invalid custom field"
  }
}

**Comment by dontinelli** [comment]
In have the same behavior. It seems that the error also occurs, if the add-on is not directly accessed (i.e. used to populate forms), as after some surfing around, the whole list is overloaded with the error message, so that I can't click on the credential to be filled-in anymore. I then have to click away the (sometimes numerous) error messages, before I get access to the below credential list again.
Would be great if the error message could be disabled or displayed elsewhere.

**Comment by Oberlurch3000** [comment]
Oh... I forgot to close this thread. For me exporting all passwords to a .JSON file and reimporting them solved the issue for me. Give it a try ;).

**Comment by dontinelli** [comment]
Thank you, also solved the problem for me.
