### ISSUE TITLE
Popup window incorrectly rendered in Chrome

### ISSUE THREAD

**Issue by ruedigerkupper** [marius-wieschollek/passwords-webextension#176]
Since the last update to Chrome, the popup window is incorrectly rendered (see screenshot) such that passwords cannot be selected.

![Bildschirmfoto von 2021-05-26 12-58-03](https://user-images.githubusercontent.com/21172886/119648873-40c8d080-be22-11eb-9946-204bc2a1dc28.png)

**Comment by ruedigerkupper** [comment]
Chrome version 91.0.4472.77

**Comment by techexo** [comment]
Hello,
I can confirm this issue with Chrome Version 91.0.4472.77 (Official Build) (64-bit).
![image](https://user-images.githubusercontent.com/1850197/119657508-49260900-be2c-11eb-9c11-cfc10293624d.png)

Regards
Eloi

**Comment by snagglewest** [comment]
I can confirm with chrome also.
I have found that if you right click the partial icon in top left corner a select option opens which allows access to the passwords.  It's a cludge but at least you can still get your passwords.  Please fix quick though!!

**Comment by marius-wieschollek** [comment]
Version 2.1.2 should fix this, but the review process may take some time

**Comment by marius-wieschollek** [comment]
The update has been published and should now be distributed.

**Comment by snagglewest** [comment]
I can confirm 2.1.2 is now distributed and working.  Thanks so much for the quick fix.
Passwords ROCKS!

**Comment by ruedigerkupper** [comment]
Confirming that it works again, thanks a lot!
