### ISSUE TITLE
Popup window incorrectly rendered in Edge

### ISSUE THREAD

**Issue by drj-vk** [marius-wieschollek/passwords-webextension#177]
Same issue as #176 but in Edge browser.

The popup window is incorrectly rendered (see screenshot) such that passwords cannot be selected.

![image](https://user-images.githubusercontent.com/3773874/120326500-11fe9e80-c2e9-11eb-93c2-b73c104c5002.png)

**Comment by marius-wieschollek** [comment]
I have submitted the new version there as well (at the same time) but it's still pending review.

**Comment by drj-vk** [comment]
Clear thank you!
