### ISSUE TITLE
Add compatibility for security/telemetry-free Firefox fork LibreWolf

### ISSUE THREAD

**Issue by lorendias** [marius-wieschollek/passwords-webextension#179]
https://librewolf-community.gitlab.io/

https://gitlab.com/groups/librewolf-community/browser/-/activity

I think there is strong overlap between the users of this extension + nextcloud and users of librewolf as an effort is made to use more private, secure and independent choices -- please consider making it librewolf compatible.

Currently, post-install -- it's not possible to complete the configuration of the plugin at this link:

moz-extension://b0a0c28d-1b0c-4b65-811a-7b6adf4cbabb/html/passlink.html?action=scan-qr

The screen is white with the error message:

"The Stream API is not supported by this browser"

Please add support or a workaround if you could, thank you.

**Comment by marius-wieschollek** [comment]
As a workaround i would suggest the manual setup: https://github.com/marius-wieschollek/passwords-webextension/wiki/setup-manual

**Comment by marius-wieschollek** [comment]
Additionally, while the "Connect via link" option for Firefox does not work, the "Connect via link" option for chrome does work.

So just go to "Apps & Extensions" in the passwords app, click on "Connect via PassLink" in the Chrome entry and then click "Connect via link" in the popup window. This should trigger the normal setup process.

**Comment by lorendias** [comment]
> As a workaround i would suggest the manual setup: https://github.com/marius-wieschollek/passwords-webextension/wiki/setup-manual

I didn't realize that the 3rd bullet point on the widget was a clickable link.

I followed the instructions in Step #2 and was able to install the extension into Firefox -- LibreWolf -- Thank you for the instructions.

Potential improvements if you're open for suggestions could include sharing this [ Manual Setup ] link more prominently in the Widget maybe remove from the <ul> and add automatic underline, or make it a button that nearly blends into the background.

And / Or sharing the link on the QR page.

In any case, thank you very much for such a cool and useful extension :+1:

**Comment by lorendias** [comment]
Thank you for your work making this and doing something cool. I searched around and sent you some coffee bux to support your work.

https://www.buymeacoffee.com/mariusdavid

Cheers :)

**Comment by Tealk** [comment]
you can connect the account if you enter the login data manually via the settings

another problem is that the password generator does not work.
```{"details":{"data":{},"message":"NetworkError when attempting to fetch resource.","file":"moz-extension://982e8234-c78a-4cd7-ab3a-8aaa65a3922b/js/options.js","line":2,"stack":"get@moz-extension://982e8234-c78a-4cd7-ab3a-8aaa65a3922b/js/options.js:2:202801\n","time":1641936261700},"error":{"name":"Error","stack":["get@moz-extension://982e8234-c78a-4cd7-ab3a-8aaa65a3922b/js/options.js:2:202801",""],"string":"Error: NetworkError when attempting to fetch resource.","fileName":"moz-extension://982e8234-c78a-4cd7-ab3a-8aaa65a3922b/js/options.js","lineNumber":2,"columnNumber":202801,"message":"NetworkError when attempting to fetch resource."}}```

**Comment by marius-wieschollek** [comment]
@Tealk I can not reproduce that issue in LibreWolf using the [test server](https://test.passwordsapp.org/apps/cms_pico/pico/passwords_test).

As far as i see, the extension works normally with libre wolf

**Comment by Tealk** [comment]
the setting of firefox and LibreWolf is the same, so the same add-ons and the same user.js.
so I must assume that LibreWolf somehow blocks the connection.

**Comment by Tealk** [comment]
> @Tealk I can not reproduce that issue in LibreWolf using the [test server](https://test.passwordsapp.org/apps/cms_pico/pico/passwords_test).
> 
> As far as i see, the extension works normally with libre wolf

i can't even add one of the test accounts in librewolf

**Comment by Tealk** [comment]
> "No default configured" is just an error that appears if there is no server configured which is the case if you have no account active.

but i took the test server from your link and tried it in a new profile because i was so surprised that it worked for you.
