### ISSUE TITLE
Password field in extension settings remembers user credentials and displays them

### ISSUE THREAD

**Issue by berturion** [marius-wieschollek/passwords-webextension#18]
The password field in the app settings remembers all previously entered passwords and displays them in clear text when double clicking in it.
See:
![nextcloud password extensions settings](https://user-images.githubusercontent.com/4692881/41953906-60e3b112-79e9-11e8-8332-46d0ce8900aa.png)

The password field must not remember previously entered passwords and not display them.

**Comment by marius-wieschollek** [comment]
oh, this seems to be a result of #15. I will disable the auto completion for the field.

You can delete the value by navigating to it with the arrow key and then pressing delete.

**Comment by berturion** [comment]
Ok. Yes I know this trick. Thanks :)

**Comment by marius-wieschollek** [comment]
The new version 1.5.1d is available on the app store and should fix this issue.
