### ISSUE TITLE
[NC21] App-specific password format mismatching

### ISSUE THREAD

**Issue by Quix0r** [marius-wieschollek/passwords-webextension#181]
### System Information
- Extension Version: 2.1.2
- App Version: 2021.6.10
- Browser and Version: 78.7.0esr (64-bit)
- Client OS and Version: Debian bullseye/sid AMD64

### Steps to reproduce
1. I have Nextcloud 21.0.2 installed, it generates very long app-specific passwords (I need for this extension)
2. I go to extensions account manager to manually add the account
3. I fill in name, URL and user
2. When I paste the app-specific password in, it got rejected as the format isn't xxxxx-xxxxx-xxxxx-xxxxx-xxxxx
3. It is a very long string with no dashes in it

### Expected result
The account should be added to the extension

### Actual result
It keeps complaining about wrong format of app-specific password

### Browser log
There is no single log entry about this. Maybe an `<input>` tag prevents this?

**Comment by marius-wieschollek** [comment]
How did you generate the app password? 
Like described here: https://github.com/marius-wieschollek/passwords-webextension/wiki/setup-manual#step-2-create-a-new-app-password ?

**Comment by Quix0r** [comment]
That was not working here, the page always redirects. I created it on console: `$ ./occ user:add-app-password roland`

**Comment by marius-wieschollek** [comment]
The extension accepts only the tokens from the personal settings page, not from the cli command.

**Comment by Quix0r** [comment]
Oh, that's very unfortunate. :-/ Cannot you just add support for it? I mean, in the end it is a username/password combination that is being sent.

**Comment by marius-wieschollek** [comment]
I don't think this option is worth implementing. The normal app password option is available to all users even without a command line access and the passlink option also provides the client with an app password.
