### ISSUE TITLE
[Feature] setting to display username per password entry

### ISSUE THREAD

**Issue by GrumpyMeow** [marius-wieschollek/passwords-webextension#182]
Hi,

I've many accounts, even multiple per website (for family members). In NextCloud i've enabled the option to display the username per each password entry. In the extension the username is not displayed, thus i now have to try each entry. 
It would be very nice if there would be a setting to enable the display of username per each password entry..

Thank you for your work!

cheers, Sander

**Comment by marius-wieschollek** [comment]
Try the nightly version of the extension where this feature can be enabled in the extension settings.

**Comment by GrumpyMeow** [comment]
Very nice! I’ll try it out.
Thanks!
