### ISSUE TITLE
Applet crashes the X-server with the new  Xorg-version(1.20.12-1) Segfault

### ISSUE THREAD

**Issue by Hamath-Eltrael** [marius-wieschollek/passwords-webextension#185]
### System Information
- Extension Version: 2.1.2
- App Version: 
- Browser and Version: Firefox 89.0.2-1
- Client OS and Version: Archlinux with i3 as Windowmanager

### Steps to reproduce
1. Update to the new Xorg-server version (1.20.12-1)
2. have multiple screens
3. Start Firefox on second Monitor 
or
1. As above
2. As above
3. Start Firefox on primary Monitor and open the Extension
4. Click anywhere

### Expected result
Xorg should not Segfault

### Actual result
Xorg Segfaults

### Temporary Fix
Downgrade Xorg to version 1.20.11-1

### Browser log
this might be not related, as its not possible to copy the contents out of firefox when the whole X-server crashes

<summary>
Das Components-Objekt sollte nicht mehr verwendet werden. Es wird bald entfernt. regex.js:12:20
Unchecked lastError value: Error: Invalid tab ID: 1 background.js:18752
Unchecked lastError value: Error: Invalid tab ID: 2 background.js:18752
this.trackerList is undefined 10 background.js:524
this.trackerList is undefined 10 background.js:524
Could not establish connection. Receiving end does not exist. Error: Could not establish connection. Receiving end does not exist.
    _sendMessage moz-extension://23b489d3-acdf-44af-880e-00b74d939423/js/background.js:1
 
Object { details: {…}, error: {…} }
 _sendMessage@moz-extension://23b489d3-acdf-44af-880e-00b74d939423/js/background.js:1:11283
background.js:1:5856
Could not establish connection. Receiving end does not exist. Error: Could not establish connection. Receiving end does not exist.
    _sendMessage moz-extension://23b489d3-acdf-44af-880e-00b74d939423/js/background.js:1
 
Object { details: {…}, error: {…} }
 _sendMessage@moz-extension://23b489d3-acdf-44af-880e-00b74d939423/js/background.js:1:11283
background.js:1:5856
Unchecked lastError value: Error: Missing host permission for the tab background.js:18554
Uncaught (in promise) TypeError: can't access dead object
</summary>

**Comment by marius-wieschollek** [comment]
Segfaults in Xorg can not be fixed within the extension. You should report this to the Xorg developers as this worked in the previous version.
