### ISSUE TITLE
Password field in the extension settings can be copied in clear text in the clipboard

### ISSUE THREAD

**Issue by berturion** [marius-wieschollek/passwords-webextension#19]
Even if the password field is hidden with dots, if you copy the text with Ctrl+C or do right click -> copy, you can paste it in clear everywhere.
(sorry, I should have seen that before, to avoid making so many releases)
Also I don't know if you can do anything to prevent this as this password field is a text one (#15 ) in order to workaround a [firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1461591)
Anyway, at least, the problem is now tracked.

**Comment by marius-wieschollek** [comment]
I think as a temporary workaround i could just put spaces in there so that it looks like the password but yo can't copy it. All in all there will be no real fix for this until the bug in firefox is fixed.

**Comment by berturion** [comment]
Yes why not...
I added a comment to the firefox bug thread, I hope this will make them fix the issue faster.

**Comment by marius-wieschollek** [comment]
Well, i once reported a bug to them more than five years ago - still not fixed.
I will release a new version with the white spaces workaround soon, but if it's still not fixed when i go to work on version 2.x in autumn, i will have to look for a very permanent temporary workaround for this.

**Comment by berturion** [comment]
"very permanent temporary workaround" it sounds funny and sad at the same time, lol

**Comment by marius-wieschollek** [comment]
The newest version will fill the field with spaces so that it only looks like a password is there. As soon as a working Firefox version is released i will remove it again.
