### ISSUE TITLE
show username in suggestions

### ISSUE THREAD

**Issue by Michele64** [marius-wieschollek/passwords-webextension#192]
**Current Status**
the popup shows the target site, wich is quite useless because the popup is site specific and usually I'm aware on what page I am ;-)
there is no way to see which entry is to choose when having multiple different logins for the same address

**Feature Description**
it would be immensly useful to be able to see the username instead of the web address

**Comment by fairking** [comment]
This is how it looks:
![image](https://user-images.githubusercontent.com/13495631/141862297-0792f973-f990-493f-8a56-edeab4e26d5c.png)

**Comment by fairking** [comment]
Please guys, all those apps are not useful.
![image](https://user-images.githubusercontent.com/13495631/141863029-f6aefac1-8f4c-4145-bcf4-7963b7e5d722.png)

**Comment by fairking** [comment]
It says name, i thought it is a username. The other option is website. So it is not working as intended.
Another case if I need to show website and username.

**Comment by marius-wieschollek** [comment]
> It says name, i thought it is a username. The other option is website. So it is not working as intended.

This is working as intended because name refers to the name of the password.

>  Another case if I need to show website and username.

[There is one](https://git.mdns.eu/nextcloud/passwords/-/wikis/Users/Settings#show-username-in-list-view-advanced)

**Comment by fairking** [comment]
ok in my opinion the option `Show username in list view` must be enabled by default, 
millions of users will search for documentation and figure out how to include the username.

**Comment by marius-wieschollek** [comment]
I'm pretty convinced that most users are like me and will use a unique name to distinguish passwords. My expectation would be that users name their accounts like "Nextcloud", "Moms Nextcloud", "Annas Nextcloud" and so on instead of using the same name for all entries. That completely defeats the reason of the name field.

**Comment by fairking** [comment]
> I'm pretty convinced that most users are like me and will use a unique name to distinguish passwords. My expectation would be that users name their accounts like "Nextcloud", "Moms Nextcloud", "Annas Nextcloud" and so on instead of using the same name for all entries. That completely defeats the reason of the name field.

I didn't know there are some names. I imported 1000 passwords and I am not sure if I find some time to rename it.

Anyway, thanks for your help.

**Comment by GrumpyMeow** [comment]
I think this issue is already resolved. In "Other Settings" there is an option to "Show username next to title".

**Comment by fairking** [comment]
Thanks. It solves the problem.

![image](https://user-images.githubusercontent.com/13495631/146523815-a5b01378-2db2-46f4-85a6-464e444d0ab5.png)
