### ISSUE TITLE
Autofill Chrome Setting

### ISSUE THREAD

**Issue by haganjoe** [marius-wieschollek/passwords-webextension#194]
If Autofill in chrome is disabled (my company does not allow Google Sync etc) we disable all of Google sync features. I'm having an issue where the Nextcloud password extension isn't asking for passwords either, even though it is checked to offer and update passwords in settings.

Does this Ext request the Chrome setting to be on as well to get the popup to save new passwords?

Thanks!

**Comment by flo-mic** [comment]
Can you check if the application is allowed to send you notifications. You can see it in the extension permission section
![grafik](https://user-images.githubusercontent.com/52607335/143037430-78ca534e-2f81-43f7-a844-baeba71ad38c.png)
