### ISSUE TITLE
configure multiple nextcloud instance

### ISSUE THREAD

**Issue by mathroc** [marius-wieschollek/passwords-webextension#20]
I'm using a few nextcloud instances and I's like to access each one trough the extension, because in each instance there's password shared with users of different nextcloud instances

alternatively it would be nice to be allowed to share a folder to remote instances trough federation but I guess this would be harder if at all possible

**Comment by marius-wieschollek** [comment]
There is currently no way to use more than one account.
This is a feature planned for 2.X but this will take some time.

**Comment by SyntaxErrol** [comment]
A suggestion: those multiple accounts should be protectable with master passwords which should be required per browser session or after a configurable expiration period.

**Comment by marius-wieschollek** [comment]
@SyntaxErrol That is being implemented as [marius-wieschollek/passwords#80](https://github.com/marius-wieschollek/passwords/issues/80). (Which is why i have to rewrite the plugin as 2.x)

**Comment by marius-wieschollek** [comment]
Multiple accounts are now in the development version 2.0.0.3501

**Comment by marius-wieschollek** [comment]
This is now implemented in 2.0.0
