### ISSUE TITLE
console error (t=comment) on `let e = t.querySelectorAll('input[type="password"]')`

### ISSUE THREAD

**Issue by GrumpyMeow** [marius-wieschollek/passwords-webextension#200]
### System Information
- Extension Version: Version2.2.0
- App Version: 
- Browser and Version: Edge, Version 96.0.1054.34 (Official build) beta (64-bit)
- Client OS and Version: Ubuntu Linux

### Steps to reproduce
1. Open Zyxel T50 modem-router admin page
2. Add static dhcp lease
2. Error is displayed in console, also unable to add static dhcp lease

### Expected result
It should work.

### Actual result
My modem-router shows an error dialog, about being unable to store the static dhcp lease.
In the console i see an error:
```
       Uncaught TypeError: t.querySelectorAll is not a function
    at o.getPasswordFields (client.js:formatted:62285)
    at MutationObserver.<anonymous> (client.js:formatted:62679)
```
When debugging i see that this piece of code is hit multiple times. Most of the times "t" is of type "document". When an error is thrown, then "t" is of type "comment".
`let e = t.querySelectorAll('input[type="password"]')`

### Browser log
       Uncaught TypeError: t.querySelectorAll is not a function
    at o.getPasswordFields (client.js:formatted:62285)
    at MutationObserver.<anonymous> (client.js:formatted:62679)

```
```
</details>

**Comment by romgere** [comment]
same behavior on Firefox (https://github.com/marius-wieschollek/passwords-webextension/issues/202)

**Comment by GrumpyMeow** [comment]
Thanks!
