### ISSUE TITLE
Remove language specific characters from the generated passwords

### ISSUE THREAD

**Issue by muashieWuphu** [marius-wieschollek/passwords-webextension#201]
**Current Status**
When I generate a new password using the extension, I get for example "KlubZawodnikówWygrać" or "MieszkaPosłowieNrWiêzienia"

**Feature Description**
Would it be possible to replace the national (Polish in this case) letters with ASCII? Like ó changed to o, ł to l, ê to e, etc... Alternatively, manual change of the dictionary used for generating passwords to English would also resolve the problem.

**Comment by GrumpyMeow** [comment]
As far as i can tell, the passwords are generated by the Nextcloud-app via the "password.generate" service. Thus this issue should probably be reported at the project https://github.com/marius-wieschollek/passwords
