### ISSUE TITLE
no password displayed after extension upgrade

### ISSUE THREAD

**Issue by lmjst** [marius-wieschollek/passwords-webextension#205]
### System Information
- Extension Version: 2.2.1
- App Version:  2021.9.20
- Browser and Version: firefox 95.0 (64 bits)
- Client OS and Version: linux ubuntu

1. In firefox while on a login page no password is displayed in the list
2. on the nextcloud instance in  /settings/user/security my client is said to be authorized
3. So I can't use my passwords in firefox

The error log is very long:

### Browser log
<details>
<summary>Browser log</summary>

Unknown theme 0c47098d-24e6-4473-8afc-fc5bbf3dbf54 Error: Unknown theme 0c47098d-24e6-4473-8afc-fc5bbf3dbf54
    findById moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2
    getCurrentTheme moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2
    getBadgeIcon moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2
    _setBadgeTheme moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2
    _updateBadge moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2
    _updateBrowserAction moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2
    init moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2
    _notifyListeners moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2
    emit moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2
    _updateTabInfo moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2
    _refreshEvent moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2
 
Object { details: {…}, error: {…} }
 findById@moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2:791993
async*getCurrentTheme@moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2:823400
async*getBadgeIcon@moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2:822679
_setBadgeTheme@moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2:850920
async*_updateBadge@moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2:850229
async*_updateBrowserAction@moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2:849882
init/<@moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2:849500
_notifyListeners@moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2:737099
emit@moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2:736799
_updateTabInfo@moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2:763044
async*4194/a</this._refreshEvent@moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/js/background.js:2:76132
</details>

on page moz-extension://23e7772d-b047-4288-beb5-c1d092e7e282/html/passlink.html?action=scan-qr
the error is :
 PasslinkScanInstructions 
 QrStreamApiNotSupportedError 

the file https://github.com/marius-wieschollek/passwords-webextension/blob/master/src/platform/generic/_locales/en/messages.json says : 
  "QrStreamApiNotSupportedError": {
        "message": "The Stream API is not supported by this browser",
        "description": "Message used by the PassLink QR scanner when the browser does not support the required streaming api. This should never happen"
    },

Thanks

**Comment by marius-wieschollek** [comment]
upgrade the app on the server to the latest version and restart your browser

**Comment by lmjst** [comment]
Yes ! Done ! Thank you
I've  gone through :
https://git.mdns.eu/nextcloud/passwords/-/wikis/Administrators/Guides/Maintenance/Use-Nightlies
https://git.mdns.eu/nextcloud/passwords/-/jobs/13229/artifacts/raw/passwords.tar.gz
https://cloud.xx.org/apps/passwords/#/apps
https://cloud.xx.org/updater/ 
https://github.com/marius-wieschollek/passwords-webextension/wiki/setup-firefox-desktop

and restart all
to get it working
