### ISSUE TITLE
[regression] The app password must be shorter than 29 characters.

### ISSUE THREAD

**Issue by rgenoud** [marius-wieschollek/passwords-webextension#207]
System Information
    App Version: 2.2.2
    Browser and Version: Firefox 91.4.1esr
    Client OS and Version: Debian 11
   Cloud platform: Nextcloud 22.2.3 / password 2021.12.20

Hi,
Since last update, the password extension stopped working.
I found that it doesn't accept long passwords/passphrases anymore (mine is more than 30).
I wouldn't like to weaken my cloud passphrase just for the password extension !
Could the max length be reverted to something higher, say 256 or 512 if a max value is really needed ?
Thanks !

**Comment by marius-wieschollek** [comment]
I had no issue with a passphrase of 50 characters. What leads you to believe the maximum length has changed?

**Comment by rgenoud** [comment]
Well, today, I tried to find a password and the extension was not finding any.
So I went on the extension settings/user account and it told me that I have to "save my settings".
I clicked on save, but it refused with the message "The app password must be shorter than 29 characters."

I manage to get it work again by installing the old 1.9.x extension, enter the account password, and re-install the 2.2.2.

That's why I concluded that the max password value has changed.
But if you had no issue, that should be due to something else.

**Comment by marius-wieschollek** [comment]
that's not a bug. the app password requested in the settings must be exactly 29 characters long as this is how long the nextcloud app passwords are. You shouldn't use your regular password to connect any third party client to your nextcloud account.

**Comment by Quix0r** [comment]
If I generate a password with `./occ user:add-app-password <username>` I get a 72 characters long password. TBSync has easily taken this, also @Dino had no problem with it. Can you please add support for these app-specific passwords?
