### ISSUE TITLE
Issue with passwords without user name

### ISSUE THREAD

**Issue by simonspa** [marius-wieschollek/passwords-webextension#21]
Currently, the passwords-webextension always displays the user name of the respective entry found in the database. This leads to problems for passords without user name:

![image](https://user-images.githubusercontent.com/1677436/42930074-4ebe3e94-8b3c-11e8-899f-a2d8a4899d73.png)

No entry is displayed below the buttons - not the "no logins found" since there is an entry, but not the entry itself as there is no user name.

Suggestion: display the configured name of the password entry instead of the user name (or preferably both, e.g.

```
My Online Shop: my_user_name
```

which would solve both this issue and the requirement to manually relate the displayed user name to the Passwords entry name.

**Comment by marius-wieschollek** [comment]
With the current api used by the extension, you can't view the password title. So i will change it to show the website hostname instead. For Version two, i will switch to the newer api and labels will be available.

**Comment by marius-wieschollek** [comment]
With the next release, the extension will show the password name as well.
