### ISSUE TITLE
Tighter Chrome Integration with password saving

### ISSUE THREAD

**Issue by AE720** [marius-wieschollek/passwords-webextension#212]
I didn't see this referenced anywhere, nor was I able to figure out what allows this to happen but I noticed Microsoft's Autofill extension has the ability to override Chrome's built in password manager and hope it would be possible to have something like that added:
![image](https://user-images.githubusercontent.com/63013864/153209206-b786340a-3493-43c8-a13d-1f07e890b9d8.png)

Here's the extension to question and I'll update if I figure out exactly what this ability is called. https://chrome.google.com/webstore/detail/microsoft-autofill/fiedbfgcleddlbcmgdigjgdfcggjcion

**Comment by calipee** [comment]
I believe you can find more information about this here: https://developer.chrome.com/docs/extensions/reference/privacy/

**Comment by marius-wieschollek** [comment]
I checked the linked chrome documentation and also what the MS Autofill extension does.
- The chrome.privacy api only allows access to privacy related settings, e.g. disabling autofill or disabling chromes integrated password manager. It does not allow providing custom passwords to chromes autofill feature or accessing passwords stored in chrome
- Microsoft Autofill disables the integrated autofill & password features and then implements its own autofill feature with custom code.

**Comment by AE720** [comment]
> I checked the linked chrome documentation and also what the MS Autofill extension does.
> 
> * The chrome.privacy api only allows access to privacy related settings, e.g. disabling autofill or disabling chromes integrated password manager. It does not allow providing custom passwords to chromes autofill feature or accessing passwords stored in chrome
> * Microsoft Autofill disables the integrated autofill & password features and then implements its own autofill feature with custom code.

Thank you for checking in on it and clarifying what it does. Feel free to close it if you don't think it'll do any good imitating the same behavior
