### ISSUE TITLE
Add master password in chrome extension

### ISSUE THREAD

**Issue by klaushipp** [marius-wieschollek/passwords-webextension#216]
**Current Status**
When I open my chrome browser I can directly use all the passwords which are in my Passwort-App on Nextcloud.
I dont have to enter a master password.

**Feature Description**
For me since not all of my devices are save it would be a good feature to have a master password to unlock the passwords.
As far as I understood this is already available in the firefox extension, right?

**Comment by marius-wieschollek** [comment]
https://git.mdns.eu/nextcloud/passwords/-/wikis/Users/Encryption/Enable-End-to-End-Encryption
