### ISSUE TITLE
[Feature Request] add PIN-Code (or systemwide used auth) to protect access to app

### ISSUE THREAD

**Issue by JimmyKater** [marius-wieschollek/passwords-webextension#217]
**Current Status**
Right now everyone on this tab could access the Passwords-app when you go away from your machine and you haven't turned on sleepmode or such

**Feature Description**
Is it possible to add an option to kind of password-protect this app with a PIN or fingerprint or similar to access app?

**Additional context**
I'm running FF on win 10 - but that's not important.

**Comment by marius-wieschollek** [comment]
Here: https://git.mdns.eu/nextcloud/passwords/-/wikis/Users/Encryption/Enable-End-to-End-Encryption
And here: https://git.mdns.eu/nextcloud/passwords/-/wikis/Users/Settings#login-session

**Comment by JimmyKater** [comment]
@marius-wieschollek 
Thanks for pointing me into these directions. But neither do I wanted an enchryption nor could I find anything like an additional PIN to protect accessing app on browserlevel.

Anyways... I feel that it might not be able including such a thing. 

Thanks though for all your wonderful work and keep it going.
