### ISSUE TITLE
can not open manual page under FF -  NetworkError when attempting to fetch resource..

### ISSUE THREAD

**Issue by Originalhardy** [marius-wieschollek/passwords-webextension#221]
Since some days I  get errors in the FF addon and I tried to resolve it. On my nextcloud server I get the following when trying to open the manuals page:
***************
 Handbuch
💀 Die Seite kann nicht angezeigt werden: NetworkError when attempting to fetch resource..
***************
It is German for: Page can not be displayed.
I an running on nextcloud 22.2.3
Any hints on what might be the issue?

The debug of the FF addon shows the following when trying to save username, password and hostaddress:
{"details":{"data":{},"message":"PasswordsClient not found","file":"moz-extension://6484fc0a-3658-46a1-8a9f-7bab35d6fda8/js/background.js","line":2,"stack":"findById@moz-extension://6484fc0a-3658-46a1-8a9f-7bab35d6fda8/js/background.js:2:780955\n","time":1647948841604},"error":{"name":"Error","stack":["findById@moz-extension://6484fc0a-3658-46a1-8a9f-7bab35d6fda8/js/background.js:2:780955",""],"string":"Error: PasswordsClient not found","fileName":"moz-extension://6484fc0a-3658-46a1-8a9f-7bab35d6fda8/js/background.js","lineNumber":2,"columnNumber":780955,"message":"PasswordsClient not found"}}
{"details":{"data":{},"message":"No default configured","file":"moz-extension://6484fc0a-3658-46a1-8a9f-7bab35d6fda8/js/background.js","line":2,"stack":"getDefaultApi@moz-extension://6484fc0a-3658-46a1-8a9f-7bab35d6fda8/js/background.js:2:762189\n","time":1647948841607},"error":{"name":"Error","stack":["getDefaultApi@moz-extension://6484fc0a-3658-46a1-8a9f-7bab35d6fda8/js/background.js:2:762189",""],"string":"Error: No default configured","fileName":"moz-extension://6484fc0a-3658-46a1-8a9f-7bab35d6fda8/js/background.js","lineNumber":2,"columnNumber":762189,"message":"No default configured"}}

**Comment by marius-wieschollek** [comment]
The error in the extension makes it look like there is no active account set up in the extension.

The network error in the handbook makes it look like whatever url is configured for the handbook does not work. I checked the default (GitHub) and it works.

**Comment by flo-mic** [comment]
@Originalhardy the handbook error is probably related to a Content-security-Header. You need to allow the guthub wiki pages of the password repo

**Comment by marius-wieschollek** [comment]
Usually the CSP is set by the app automatically. If its overridden you can need to update it. If you can't for any reason allow the handbook to be fetched from an external source you can use the passwords handbook app to serve it locally.
