### ISSUE TITLE
Use local IP for URL setting in Chrome Browser Extension

### ISSUE THREAD

**Issue by snowwolf3388** [marius-wieschollek/passwords-webextension#224]
### System Information
- Extension Version: 2.2.4
- App Version: 23.0.3
- Browser and Version: Chrome Version 100.0.4896.88 (Official Build) (64-bit)
- Client OS and Version: Windows 10 Home 19043.1645

### Steps to reproduce
1.  

Try to change my browser extension settings, from an external URL (https://nextcloud.mydomain.com) to an IP Address (http://10.0.0.100:port#). Also tried to add a new user with these settings and it also didn't work. 

4.  None.
5.  None.

### Expected result
What should happen?
I would think that it should resolve the url and find my nextcloud instance regardless of if I'm using a full URL or an IP address and port for my local network. I have an issue with my new router that doesn't like hairpinning, so I need to access my services from inside my network via their local address, rather than external url.

### Actual result
What does happen?
The settings don't work and don't save. I see either Failed to Fetch or "Base Url Missing or Invalid".

### Browser log
<details>
<summary>Browser log</summary>

```
In Firefox:
 - Open about:debugging#/runtime/this-firefox
 - Click "Inspect" on the extension
 - Copy the content from the "Console" tab

In Chrome
 - Open chrome://extensions
 - Enable "Developer mode" in the top right corner
 - Click "Background page" on the extension
 - Copy the content from the "Console" tab
```
</details>

**Comment by marius-wieschollek** [comment]
I didn't expect the validation to fail that fast when creating the form. Usually there is a message informing you that HTTP is not a supported protocol. I was able to connect to a HTTPS server via IP successfully as long as the connection was done with a certificate that was accepted by the browser.
