### ISSUE TITLE
More options in generate password - Every password includes Euro € symbol

### ISSUE THREAD

**Issue by misterfitz** [marius-wieschollek/passwords-webextension#226]
**Current Status**
Creating a password only has Low----Ultra options and Numbers or Symbols on/off toggle. Many US websites only accept some basic symbols. 

**Feature Description**
Be able to include basic not all symbols. Or be locale aware and friendly.

**Comment by marius-wieschollek** [comment]
Passwords are generated by the app, there is a ticket to do that change there
