### ISSUE TITLE
Chromium fails with too many redirects

### ISSUE THREAD

**Issue by nicman23** [marius-wieschollek/passwords-webextension#23]
basically my server 302 to:
apps/passwords/api/0.1/passwords
until it fails.

however, the firefox version works fine.

**Comment by marius-wieschollek** [comment]
Can you check if there are any relevant entries in the nextcloud log?
Do you have the legacy api enabled.

**Comment by nicman23** [comment]
yes legacy api is enabled and nextcloud does not log anything about the retries

**Comment by marius-wieschollek** [comment]
This is probably the same issue as #25. Please see my latest comment there to resolve it.
