### ISSUE TITLE
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

### ISSUE THREAD

**Issue by barrydegraaff** [marius-wieschollek/passwords-webextension#231]
When running this extension I see:
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

You may want to support the next version for continued use.

**Comment by marius-wieschollek** [comment]
> You may want to support the next version for continued use.

_Wan't_ isn't the word i would use, but it's going to be necessary to migrate the extension in the coming months.

**Comment by ssiergl** [comment]
@marius-wieschollek 

Unfortunately, the time has come… Google is currently removing all plugins with the old Manifest V2.0. On some of our laptops, the extension has disappeared and can no longer be installed from the Chrome Extension Store.

Could you perhaps update to Manifest 3.0? It would be a shame if such a great extension stopped working.

Thanks and regards,

Lars

**Comment by marius-wieschollek** [comment]
Oh, is this already happening.
Well then i will push the update for Chrome & Edge.
Should be there in a few days but it will be missing some features as these aren't available with the new restricted api

**Comment by ssiergl** [comment]
Thanks for your hard work on this extension! :)

Do you already know which features will be missing?

**Comment by marius-wieschollek** [comment]
I think it's autofill for HTTP basic auth and clear clipboard after password copy

**Comment by marius-wieschollek** [comment]
A quick update:

Google has rejected the update because of a (now) unused clipboardRead permission, but they allowed the development build to be updated.
Microsoft has published the update.

I have reviewed the permissions and resubmitted the extension.

**Comment by marius-wieschollek** [comment]
So, it should be available in all app stores by now and on https://extensions.passwordsapp.org/

I will see if  the currently missing features can be restore in the future. If anyone has any ideas on that, feel free to make a PR.

**Comment by ssiergl** [comment]
Thank you for the extremely quick solution and implementation! Excellent work :)

**Comment by shining-cat** [comment]
Thanks for the fix!!
