### ISSUE TITLE
Auto lock for extension

### ISSUE THREAD

**Issue by alephtaph** [marius-wieschollek/passwords-webextension#239]
**Current Status**
As a user, I start my browser in the morning and enter the encryption password to enable the web extension. Now the extension stays open until I restart my browser. This way, if someone leaves the desk and does not lock the computer, someone else has access to all passwords.

**Feature Description**
Other password manager have different options to be set, like:
- lock vault when locking computer
- lock vault after 5, 10, 15 minutes
After let's say 5 minutes, the vault locks and the user needs to enter the encryption password to open the vault.

**Comment by marius-wieschollek** [comment]
The extension actually supports half of the requested feature. If you're using an encryption password, you can set it to log out automatically.
To do so, open the extension popup, click on the "tools" tab, then click on "open settings". You should see a list with you user accounts. Click on any account with an encryption password and there you can set the logout time.

The extension does not yet support an option to log out if your device is locked, but i checked the documentation and the [idle api](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/idle) should be able to provide the necessary information to build that feature.

**Comment by alephtaph** [comment]
Great that is already what I would need. Now I just need a way to set the encryption password as mandatory and the lock time as an administrator. Do you see an option to set it via registry, at least the part with the logout after some minutes?

I saw you reply about the Feature Management with the first run wizard. This is a bit weak since user can skip. Are you aware how other companies solve this issue?

**Comment by coffseducation** [comment]
> enter the encryption password to enable the web extension.

Sorry to bump this thread, but I feel stupid to start a new issue for what I assume it simple, but how do you set an encryption password?
I see app password in the extension but this does not appear to do anything.
Thanks.
