### ISSUE TITLE
Show Name instead of Username in list of passwords

### ISSUE THREAD

**Issue by Morgenkaff** [marius-wieschollek/passwords-webextension#24]
Its getting a little confusing when I'm visiting a site where I have multiple accounts, or have multiple passwords for different functions, but tied to the same mail/username.

For example:
![image](https://user-images.githubusercontent.com/6614737/43766977-29a33f0e-9a34-11e8-9c24-1b85bbaa9f75.png)

I have differentiated them in their names. But when on the site they are used, the extension shows the username/mail.

It would be nice if the extension showed the name field instead of username, or at least had a option to show the name.

**Comment by marius-wieschollek** [comment]
See my comment on [issue 21](https://github.com/marius-wieschollek/passwords-webextension/issues/21#issuecomment-410540220)
