### ISSUE TITLE
cannot change "Logout after" from "Never" to 60 minutes

### ISSUE THREAD

**Issue by meonkeys** [marius-wieschollek/passwords-webextension#245]
### System Information
- Extension Version: 2.2.6
- App Version: 2022.11.21
- Browser and Version: Firefox 106.0.3 (64-bit)
- Client OS and Version: Ubuntu 22.04.1 LTS 64-bit Desktop

### Steps to reproduce
1. Navigate to extension settings
2. click Preferences
3. click on a user account
4. change "Logout after" from "Never" to 60 minutes
5. close browser
6. navigate back to this setting

### Expected result
Setting is at 60 minutes.

### Actual result
Setting is at "Never"

### Browser log
<details>
<summary>Browser log</summary>

```
Element.releaseCapture() is deprecated. Use Element.releasePointerCapture() instead. For more help https://developer.mozilla.org/docs/Web/API/Element/releasePointerCapture
```
</details>

**Comment by marius-wieschollek** [comment]
Is this issue still present in the current version?

**Comment by meonkeys** [comment]
Works for me in 2.4.0.
