### ISSUE TITLE
Firefox: extension does not connect after startup

### ISSUE THREAD

**Issue by ascpial** [marius-wieschollek/passwords-webextension#246]
If the Nextcloud instance is not reachable by the browser at startup, the extension never connects and you need to restart the browser, which can be annoying in a lot of situations.

### System Information
- Extension Version: 2.2.6
- App Version:  2022.11.21
- Browser and Version: Firefox 106.0.4 (64-bit)
- Client OS and Version: Fedora 37

### Steps to reproduce
1. Make sure the Nextcloud instance is unreachable (wifi off, wrong proxy settings, instance down... a lot of things can go wrong)
2. Start the browser
3. Make the Nextcloud instance reachable (turn the wifi on, correct the proxy settings, start the instance...)

### Expected result

The extension should connect to the instance and activate the features.

### Actual result

The extension never connects, and clicking on the icon show the interface with no passwords at all.

### Browser log

<details>
<summary>Browser log (when the instance is unreachable)</summary>

```
NetworkError when attempting to fetch resource. TypeError: NetworkError when attempting to fetch resource. 
Object { details: {…}, error: {…} }
 <empty string> [background.js:2:733345](moz-extension://e6b9255a-b02e-4d03-bff1-a6808fc0f04d/js/background.js)
    _addError moz-extension://e6b9255a-b02e-4d03-bff1-a6808fc0f04d/js/background.js:2
    logError moz-extension://e6b9255a-b02e-4d03-bff1-a6808fc0f04d/js/background.js:2
    init moz-extension://e6b9255a-b02e-4d03-bff1-a6808fc0f04d/js/background.js:2
Could not establish connection. Receiving end does not exist. Error: Could not establish connection. Receiving end does not exist.
    _sendMessage moz-extension://e6b9255a-b02e-4d03-bff1-a6808fc0f04d/js/background.js:2
 
Object { details: {…}, error: {…} }
 _sendMessage@moz-extension://e6b9255a-b02e-4d03-bff1-a6808fc0f04d/js/background.js:2:796340
[background.js:2:733345](moz-extension://e6b9255a-b02e-4d03-bff1-a6808fc0f04d/js/background.js)
    _addError moz-extension://e6b9255a-b02e-4d03-bff1-a6808fc0f04d/js/background.js:2
    logError moz-extension://e6b9255a-b02e-4d03-bff1-a6808fc0f04d/js/background.js:2
    _sendMessage moz-extension://e6b9255a-b02e-4d03-bff1-a6808fc0f04d/js/background.js:2
```
</details>

**Comment by MrManor** [comment]
As a person who often have to log out/in to different user accounts this is really annoying. My desktop environment automatically restarts every application running at last shutdown, thus Firefox always restarts before my wifi connects. 

I will note though, that one can avoid restarting firefox by entering the extension settings, and flipping the Disable/Enable switch
