### ISSUE TITLE
Automatically display Suggestions after unlocking

### ISSUE THREAD

**Issue by TtuxX** [marius-wieschollek/passwords-webextension#254]
### Steps to reproduce
1. Have E2E Encryption enabled
2. Load a fresh browser 
3. Go to a website that you have in the Passwords app
4. Type your password to unlock Passwords Webextension
5. Expect to see Suggestions tab refresh and load the corresponding password suggestion
6. See that nothing shows up and that you have to click on Search tab (or any other one), then go back to Suggestions to finally see the matching passwords appear

### Expected result
When the Webextension is unlocked, Suggestions tab should immediately refresh and you should be able to see your suggestions without having to use a trick to force refresh its content

### Actual result
No Suggestions show-up as long as you do nothing (click action on another tab of the extension or something similar)

**Comment by marius-wieschollek** [comment]
Has this issue been resolved with the newer updates? The list should now reload after a few seconds and show the data.

**Comment by TtuxX** [comment]
Hi Marius, 

Yes, it works perfectly fine now! Thank you so much !! :)

**Comment by TtuxX** [comment]
Hello Marius,

Would it also be possible, upon unlocking, to automatically trigger a paste action if the page we are on is in database ?

Example: when I unlock the app, it is always at a moment where I am on a website, expect the credentials to be pasted, but find the Passwords extension to be locked again. Upon unlocking it, it would be awesome to also have it automatically paste any credentials it might find for the active tab. 
As of today, upon unlocking, I always have to manually trigger the paste action (which then works fine for any new tab that is being opened).

Many thanks in advance for your kind help

**Comment by marius-wieschollek** [comment]
I can look into that. Can you please make a new ticket for this?

**Comment by TtuxX** [comment]
Of course ! Thank you very much Marius :)
You will find it in ticket https://github.com/marius-wieschollek/passwords-webextension/issues/270
