### ISSUE TITLE
do not close add-on pop-up on focus loss

### ISSUE THREAD

**Issue by jficz** [marius-wieschollek/passwords-webextension#255]
**Current Status**
The addon popup window (the one that show when the addon icon in toolbar is clicked) is closed/hidden immediately when the browser window loses focus. Tested on Firefox (LibreWolf) and Chromium (Brave).

**Feature Description**
The window should optionally only close on explicit action such as:
- clicking outside the window (but inside the browser window)
- pasting creds
- copying generated password
- pressing ESC or clicking a close button
- etc.

**Additional context**
Closing the window on focus loss breaks many useful use-cases, for example:
- entering the master password using local `pass-dmenu` or other similar password operators
- copy-pasting multiple things to/from the window
- re-typing the password manually to sites/places which are disconnected from the browser window (like RDP sessions)
- any other workflow which requires focus switch

**Comment by marius-wieschollek** [comment]
This behavior can not be controlled by the extension.
