### ISSUE TITLE
autofill suggestions not shown after logging in, must click away and return

### ISSUE THREAD

**Issue by meonkeys** [marius-wieschollek/passwords-webextension#260]
### System Information

- Extension Version: 2.3.0
- App Version: 2023.8.31
- Browser and Version: Firefox 115.0.2
- Client OS and Version: 64-bit Ubuntu 22.04.2 LTS Desktop

### Steps to reproduce
1. Open Firefox.
2. Click key icon to log in to unlock passwords database using master password.
3. With login complete, the extension's popup window refreshes, showing the "Suggestions" tab.

### Expected result
Suggestions tab shows password autofill suggestions for current tab.

### Actual result
Suggestions tab is blank.

### Workarounds
1. Manually switch the tab from Suggestions to Search. Suggestions appear.
2. Close the popup window, click the key to open it again. Suggestions appear.

### Browser log
n/a

**Comment by meonkeys** [comment]
Awesome! Let me know if you'd like me to help test/QA this fix.

**Comment by marius-wieschollek** [comment]
This should be working in any stable release by now

**Comment by meonkeys** [comment]
Yep, works for me in 2.4.0, after waiting a few seconds.
