### ISSUE TITLE
Can't install the extension on Brave browser

### ISSUE THREAD

**Issue by jespernykilde** [marius-wieschollek/passwords-webextension#261]
### System Information
- Extension Version: 2.3.0
- App Version:
- Browser and Version: Brave [Version 1.57.47 Chromium: 116.0.5845.96 (Officiel version) unknown (64-bit)]
- Client OS and Version: Tuxedo OS 2. KDE Plasma-version 5.27.7 Kernel-version: 6.2.0-10018-tuxedo (64 bit)

### Steps to reproduce
1. 
2. 
3. 

### Expected result
What should happen? I should be able to install the extension and use it. But I can't even get to install it.

### Actual result
What does happen? Nothing, no install

### Browser log
<details>
<summary>Browser log</summary>

```
In Firefox:
 - Open about:debugging#/runtime/this-firefox
 - Click "Inspect" on the extension
 - Copy the content from the "Console" tab

In Chrome
 - Open chrome://extensions
 - Enable "Developer mode" in the top right corner
 - Click "Background page" on the extension
 - Copy the content from the "Console" tab
```
Not possible, as it is impossible to install the extension at all.

**Comment by marius-wieschollek** [comment]
I can't reproduce this issue if you don't fill in the necessary information. The extension installs just fine on Brave.

**Comment by jespernykilde** [comment]
Hello

I believe I did fill in all the information possible, but I'll attach 3 screenshots here:

![Screenshot_1](https://github.com/marius-wieschollek/passwords-webextension/assets/119656724/bf6fa5f1-4fc2-4cf1-8db6-21409bf095d6)
![Screenshot_2](https://github.com/marius-wieschollek/passwords-webextension/assets/119656724/41cf48a3-15bf-4b1e-b0e0-4b15977695cd)
![Screenshot_3](https://github.com/marius-wieschollek/passwords-webextension/assets/119656724/4f4694f3-e578-4df1-9225-1f8b44f56f7c)

**Comment by marius-wieschollek** [comment]
That was the information i needed. You can try to install the beta version from here: https://chrome.google.com/webstore/detail/passwords-for-nextcloud-b/aipncmjoigmhooiiclcailmhiopachih which should no longer have that issue.

**Comment by jespernykilde** [comment]
Thanks, that did it.
