### ISSUE TITLE
Edit Passwords and Notes through the extension

### ISSUE THREAD

**Issue by unix0r** [marius-wieschollek/passwords-webextension#27]
What about a feature to access (thats already built in for passwords) and edit passwords and their notes through the extension.

Sometimes the Extension does not recognize a new password and does not ask to change it. So the password could be set manually.
And the access to notes of the passwords would also be great, so you do not have to login to your nextcloud instance for some information and could grab or edit them directly through the extension.

What do you think about that?

**Comment by misterbridge** [comment]
I think this should stay low impact on the webextension UI, maybe just a link to the app, opening the password's description/edition ?

**Comment by godfuture** [comment]
Same for me. Often dynamic websites have special login forms that are not recognized from this addon. I would like to be able to manually a password then.

**Comment by majkinetor** [comment]
Just opening it on next cloud per se (with current URL added to the website field) would be enough IMO. That is how many other password managers handle it.
