### ISSUE TITLE
Warning about needing a new version that hasn't been released yet

### ISSUE THREAD

**Issue by admorgan** [marius-wieschollek/passwords-webextension#271]
### System Information
- Extension Version: 2.5.0
- App Version: 2023.11
- Browser and Version: Vivaldi 6.4.3160.44
- Client OS and Version: OpenSUSE Tumbleweed

### Steps to reproduce
1. open the extension
2. Warning that the extension will soon require Passwords 2023.12

### Expected result
No warning is displayed

### Actual result
Warning is displayed, despite no action being available to the user since 2023.12 has not been released.

**Comment by marius-wieschollek** [comment]
Version 2.5.0 has also not yet been released :wink: This is currently the development version.

It will be released alongside 2023.12 which will be released alongside Nextcloud 28 on the 12 of December.
