### ISSUE TITLE
A lot of sessions open by the extension in Nextcloud

### ISSUE THREAD

**Issue by llaumgui** [marius-wieschollek/passwords-webextension#274]
### System Information
- Extension Version: 2.5.0
- App Version: 2023.12.31
- Browser and Version: Firefox 120.0.1
- Client OS and Version: Fedora 39

### Steps to reproduce
1. Use last extension for firefox.
2. Go to /settings/user/security
3. Check an important number of session in same time and every minuts.

### Expected result
No so sessions.

### Actual result
A lot of sessions.

**Comment by marius-wieschollek** [comment]
This extension does not open any new sessions that would be shown in /settings/user/security.

You're probably experiencing this behavior here: https://github.com/marius-wieschollek/passwords/issues/621#issuecomment-1856253948
