### ISSUE TITLE
Show additional information

### ISSUE THREAD

**Issue by mokkin** [marius-wieschollek/passwords-webextension#28]
Additional information such as notes on passwords should be show for examp on mouse over.
Sometimes you have different logins just with number as username. So you could specify some hints which user it is.

**Comment by marius-wieschollek** [comment]
I would say this is related to #27

**Comment by d-tamm** [comment]
![bild](https://user-images.githubusercontent.com/9801554/53864915-029b2880-3fee-11e9-8865-347d83bad0a3.png)
I second this request. The current behaviour makes it sometimes very difficult to use the extension. As an example, attached a screen shot where I have accounts at different subdomains or ports, with the same user name but not necessarily with the same password. No way to tell apart the two admin accounts.
I propose to not only show the user name in the interface, but also the user defined name for that post, at least if there are publicate user names in the current list. E.g. "admin - My Webmail" and "admin - Home NAS".

**Comment by misterbridge** [comment]
Simply show the password's name as in the app's list instead of the username would be great as we can customize it as we like. (or make it an option switch)

**Comment by marius-wieschollek** [comment]
The missing names seem to be an issue which annoys a lot of people. So i will extend the legacy api to contain the name and display it in the extension in the next update.
