### ISSUE TITLE
[FEATURE]: Menu for autofill

### ISSUE THREAD

**Issue by gelbphoenix** [marius-wieschollek/passwords-webextension#287]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **feature request** for _one_ feature, not a question, discussion or multiple features.
- [X] This is not a feature request for the [Nextcloud App](https://github.com/marius-wieschollek/passwords) or another client.
- [X] This feature is **not** already requested on Github _(I've searched it)_.
- [X] This feature does not already exist _(I checked the [wiki](https://git.mdns.eu/nextcloud/passwords/-/wikis/Users/Browser-Extension))_.

### Current Status

At the status quo the extension only can autofill the first possible and found entry for an login form. If autofill is deactivated a user must copy the details into the form manually. If automatic deletion of passwords in the clipboard is not activated this can be a security risk.

### Feature Description

If a user wants to login a dropdown menu with found passwords should appear where the user can choose the login data for the account the user wants to log into.

### Additional Context

Personally i see this as an should have feature which could be placed as an option for the autofill already existing in the web extensions.

Besides that this is an feature major password managers already have. For example: 

Bitwarden:
![image](https://github.com/user-attachments/assets/36eed77a-783e-4306-8bbb-618d16f3a73a)

**Comment by marius-wieschollek** [comment]
You know that even with autofill disabled, the extension will paste the credentials into the login form (if detected as such) when you just click on the entry in the suggestions?

**Comment by gelbphoenix** [comment]
I actually didn’t know that. Am 29.07.2024 um 22:17 schrieb M. Wieschollek ***@***.***>:﻿
You know that even with autofill disabled, the extension will paste the credentials into the login form (if detected as such) when you just click on the entry in the suggestions?

**Comment by gelbphoenix** [comment]
Closing feature request because it's unnecessary.
