### ISSUE TITLE
Doesn't propose login on Android

### ISSUE THREAD

**Issue by freijon** [marius-wieschollek/passwords-webextension#29]
With Firefox Android, when I'm viewing a login-page and I open the "Passwords" window via the three-dot-menu, a new tab opens with a **moz-extension://** URL. But this new tab doesn't propose me the login for the page that was previously showing. Instead, it shows "No logins found".

**Comment by marius-wieschollek** [comment]
Usually related passwords will also work on Firefox for Android.
It could be possible that the page you're viewing is on a subdomain (Like http://m.example.net) and therefore the domain does not match up.
Can you check if you can find the password in the search tab?

**Comment by freijon** [comment]
You are right. The mobile page has a subdomain whereas the desktop site does not. I must have overlooked this. Is it possible to add wildcards to URLs or to add multiple URLs?

**Comment by marius-wieschollek** [comment]
You can already add other urls as a custom field, but those are currently not being used by the extension. When the next major version comes there will be a feature to make use of those urls. (See #14)
