### ISSUE TITLE
Autofill login forms

### ISSUE THREAD

**Issue by florealcab** [marius-wieschollek/passwords-webextension#30]
Currently, we login by opening the extension and click on the user.

I think it should be nice if we could also use the default login form, as the plugin autofill it for us.

It is required if we use chrome with an app: we have no toolbar in this case, so we can't access the extension button.

**Comment by marius-wieschollek** [comment]
Currently this is not supported, but i will add it when with the next major release

**Comment by misterbridge** [comment]
Just for info, when do you think will v2 be out ?
Like, in a month, 6 month or a year ?

**Comment by marius-wieschollek** [comment]
Probably 6 months. It depends on [Passwords#80](https://github.com/marius-wieschollek/passwords/issues/80). After that is finished i will work on the new version of the extension using the new api which supports a lot more than the old one.

**Comment by misterbridge** [comment]
New version is out and it "kinda works" but actually it doesn't as expected:
It won't autofill by itself on page load. One needs to leave the chrome tab and get back to it for the form to autofill. Kinda weird.
