### ISSUE TITLE
 extension problems

### ISSUE THREAD

**Issue by jookk** [marius-wieschollek/passwords-webextension#31]
![token](https://user-images.githubusercontent.com/11217085/47256293-e1420180-d47d-11e8-83b0-097289af960b.png)
I connected to my nc 14.03 instance via app passwords. 
Connect to nc - successfull
But, I cant save password, i cant load passwords - see picture.

**Comment by jookk** [comment]
![screenshot_20181020-161100 2](https://user-images.githubusercontent.com/11217085/47256605-56640580-d483-11e8-9a2f-3c7c6c1a281a.png)
Also in Firefox for android beta

**Comment by marius-wieschollek** [comment]
Can you please check if you have the "Legacy Api Enabled" option enabled.

**Comment by jookk** [comment]
Thanks, it was disabled. Now all is working fine.
