### ISSUE TITLE
Do not submit login forms when the method is GET

### ISSUE THREAD

**Issue by fisharebest** [marius-wieschollek/passwords-webextension#32]
The plugin does two things:

1) it autocompletes the username/password
2) it submits the login form

I have found many sites which are built as "single page applications", and process the login form using JavaScript.

Effectively, something like this

```
<form>
<input type="text">
<input type="password">
<input type="submit" onclick="login()'>
</form>
```

Note that the `<form>` element does not have `method="POST"` or `action="url"`.

When the plugin submits this form, two things happen:

1) the page reloads with `?username=xxx&password=yyy` in the URL
2) the login doesn't actually work

Suggestion - if `form.method === 'GET'` then do not submit the form. 
Just autocomplete the fields.
Login credentials should never be sent in a GET request.

**Comment by marius-wieschollek** [comment]
Usually the extension will click the submit button of a form if it is available. Only if no submit button can be found, the submit action will be triggered directly.
I have added the check there and built a nightly version:

Assuming you are using Firefox, you can download [nextcloud_passwords_client-1.6.0.1-an+fx.zip](https://github.com/marius-wieschollek/passwords-webextension/files/2531813/nextcloud_passwords_client-1.6.0.1-an%2Bfx.zip), then unzip it and go to the addons page in Firefox.
In the menu next to the search bar select "Install addon from file" and select the xpi file.

**Comment by fisharebest** [comment]
> Assuming you are using Firefox

I am, and the updated addon works as expected.

Thanks!
