### ISSUE TITLE
Security feature wish: master password for enable webextension

### ISSUE THREAD

**Issue by audioprog** [marius-wieschollek/passwords-webextension#33]
when sharing an user account all other have the passwords.

For security reasons the webextension could set to disabled by elapsed time and for enabling it, it can ask for master password.

**Comment by marius-wieschollek** [comment]
The client side encryption will add the option for a master password and timeouts to the passwords app, so it would be a good opportunity to implement it into the browser extension as well.

**Comment by fridlmue** [comment]
would be great to get this even coupled with nextclouds u2f feature!

**Comment by marius-wieschollek** [comment]
The master password is now available trough e2e in the extension. the auto-logout will be implemented in #69
