### ISSUE TITLE
Websites with Additional Account Fields

### ISSUE THREAD

**Issue by BrianEnders** [marius-wieschollek/passwords-webextension#34]
On some websites, there is an additional field for an Account Number before using a Username and Password. When using the extension, the username will be placed in the Account Number instead. Here is an example website of what I mean:

http://adpcrm2.v-sept.com/Common/Pages/Authentication/Login.aspx

**Comment by flo-mic** [comment]
@BrianEnders this issue is quite old, but the feature is implemented in the nightly build. You can add additional "FormFields" as custom fields in the extension. The FormField name is the ID of the login field and the value is the value to place in the field.
