### ISSUE TITLE
Nextcloud address and username reset after entering password

### ISSUE THREAD

**Issue by madmath03** [marius-wieschollek/passwords-webextension#35]
Hi Marius,

I encountered a weird behavior with the Chrome extension:
* I install the Chrome extension (Chrome Version 71.0.3578.98 (Build officiel) (64 bits))
* I enter my Nextcloud URL
* I enter my Nextcloud username
* I enter my Nextcloud password **and suddenly the Nextcloud URL and username are emptied**

I managed to reproduce this everytime. After entering the first letter, the URL and username are immediately reset.

If I first enter the password then URL and username, I can actually save the configuration and everything seems to work, but this weird behavior also happens if I want to update my configuration.
For instance, let's say I set the following information:
* URL: `https://my.nextcloud.com`
* User: `my.bad.username`
* Password: `somethingverysecret`

Then, if I first change my user from `my.bad.username` to `my.username` then change the password, I can see my username being reset to `my.bad.username`.

I did not look through the code but there must be some kind of "_reset to last save config_" function which is triggered when updating the password.

**Comment by marius-wieschollek** [comment]
You can try the attached version for a bugfix. It also has a dark mode which should fix #36 .
[passwords-webextension-1.7.0.0.zip](https://github.com/marius-wieschollek/passwords-webextension/files/2683859/passwords-webextension-1.7.0.0.zip)

**Comment by SuziQ407** [comment]
Hello Marius,
same problem here with FF 64.0 on Linux: Typing first character of the password empties the fields URL and Username. FF Add-on version 1.6.0.3.

**Comment by marius-wieschollek** [comment]
Version 1.7.0 has been released and should fix the issue.
