### ISSUE TITLE
Web Extension logo with a background?

### ISSUE THREAD

**Issue by madmath03** [marius-wieschollek/passwords-webextension#36]
Hi,

I know this is a very suggestive request, but the Chrome extension logo is only a key with no background. I use a dark theme for Chrome which unfortunately uses pretty much the same background color as the extension's icon color, which makes it "_invisible_".
![image](https://user-images.githubusercontent.com/6967675/50053761-b8b34c80-013a-11e9-9e78-3d39dcb231d1.png)

Most of nowadays Web Extensions seems to use a logo with a background color. I'm guessing this is to always be visible no matter the user theme configuration.
Would it be possible to "_improve_" the logo by adding a background color to it?

**Comment by marius-wieschollek** [comment]
Version 1.7.0 has been released and offers a dark mode which fixes the issue.

**Comment by madmath03** [comment]
Hello Marius,

Indeed, the release 1.7.0  offers a dark mode which will switch the icon to something visible even when using a dark Chrome theme... but I was not expecting the Passwords screen to also turn to the dark(ish) side.

It kind of makes sense to offer a complete dark experience (I would personnaly love it), but either I encountered a bug in the display either I suggest you rework the colors for dark mode because the current display is really hard to read:
![image](https://user-images.githubusercontent.com/6967675/50400616-3e14ad80-0788-11e9-8332-f0aa67043e01.png)

Usually, dark modes tend to switch background-color to a blackish color (not a full black though, more like `#222222` or `#333333`) and the color to a light gray (something like `#c0c0c0` or `#a0a0a0`) which makes it easy on the eye and easy to read.

You might want to checkout NextCloud 14 dark mode to try to offer a consistent display: https://www.youtube.com/watch?v=S_842AQx3MQ

By the way, now that I think about it, I'm wondering if that would be possible to automatically retrieve the NextCloud theme color, and possibly the accessibility theme, to apply it to the Passwords extension.
Does it make sense ?

If it does, I might create a new issue to track the request.

Anyway, thank you much for your amazing work.

**Comment by marius-wieschollek** [comment]
> It kind of makes sense to offer a complete dark experience (I would personnaly love it), but either I encountered a bug in the display either I suggest you rework the colors for dark mode because the current display is really hard to read

That looks like a bug. Can you tell me which dark theme / extension you are using?

> By the way, now that I think about it, I'm wondering if that would be possible to automatically retrieve the NextCloud theme color, and possibly the accessibility theme, to apply it to the Passwords extension.
That does make sense, and the app actually supports this with the new api. But this extension is older than the app and still uses the legacy api, so it can't access the info.
As soon as i have time to rewrite the extension, i will also make sure to include proper theming support.

**Comment by madmath03** [comment]
I am using Chrome "_Dark Theme v3_" of Marco De la Cruz:
https://chrome.google.com/webstore/detail/dark-theme-v3/djlgdeklopcjagknhlchbdjekgpgenad

Just to make sure, I reverted the theme to Chrome default, restarted browser, and still see the same display in dark mode.
For information I am using Google Chrome Version 71.0.3578.98 (Build official) (64 bits)

Would you like me to open a separate issue or do you wish to keep tracking it here ?
