### ISSUE TITLE
button to click in pop-up

### ISSUE THREAD

**Issue by lostinbits** [marius-wieschollek/passwords-webextension#37]
Hi Marius,
Would it be helpful and possible to have buttons in the pop-up when saving a password in firefox? So you can clear choose to save or not save a password to your nextcloud?

**Comment by marius-wieschollek** [comment]
I would like to do this. The WebExtension API specifies that the notification can have two buttons, but Firefox and Edge do not implement this (see [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications/NotificationOptions#Browser_compatibility)).

**Comment by lostinbits** [comment]
i see. that's to bad, it would be more clear to have the option. Then we have to wait till Firefox makes the implementation possible. Thanks for the good work!!
