### ISSUE TITLE
Cant use Extension in mobile

### ISSUE THREAD

**Issue by david883** [marius-wieschollek/passwords-webextension#38]
Hello, I use the Passwords Extension 1.7.1.0 with Firefox on Android. For a few days I can no longer retrieve a password list. There are no entries in the log on Nextcloud Server 14.04.

The extension works fine on the Windows desktop.

Any idea?

**Comment by marius-wieschollek** [comment]
Can you try to restart Firefox by closing it from the "Recent Applications" list or the settings?

The version 1.7.1 contains a fix for a bug which prevents the synchronization with the server.
Closing Firefox will make sure that the new code gets loaded properly and the client tries to synchronize again.

**Comment by david883** [comment]
Work! Excellent. Thank you
