### ISSUE TITLE
NetworkError when attempting to fetch source

### ISSUE THREAD

**Issue by KonstaX** [marius-wieschollek/passwords-webextension#39]
Hello,
So I installed password the extension yesterday it worked well but now the extension seems to not work at all it tells me 'NetworkError when attempting to fetch source'.

**Comment by CamGenius** [comment]
I am having the same issue other than it never worked at all for me. At least it worked for a little while for you.

**Comment by marius-wieschollek** [comment]
The new version 1.8.0 will have some more detailed error messages if a connection error happens. If you retry with this version you may be able to figure out what is wrong with your setup.

**Comment by jisse44** [comment]
Hi,
I have same problem, but only with Firefox for Android. On PC it's OK.
Error is (in French):
La liste des mots de passe n'a pas pu être récupérée. Erreur: URL invalid or API disabled

**Comment by marius-wieschollek** [comment]
@jisse44 The error indicates that the url entered in the settings returned a "200 OK" status but the body did not contain JSON formatted data. As the error states the most likely cause of this is an invalid url or the legacy api has been disabled in the admin settings.

**Comment by jisse44** [comment]
My bad, I didn't see that here: https://git.mdns.eu/nextcloud/passwords/wikis/Administrators/Administrative-Settings#enable-legacy-api ...
Thank you

**Comment by CamGenius** [comment]
I have the correct url and the legacy API enabled yet I still cannot get connected?

**Comment by GuepardoApps** [comment]
Had a similar on a problem after installation on Firefox for Android. Using the URL with https throws an error, couldn't connect. I updated the URL to only use http and everything works fine.
This problem doesn't occur to me on Firefox for Windows.
