### ISSUE TITLE
JSON parse error with 2018.1 app

### ISSUE THREAD

**Issue by HanFox** [marius-wieschollek/passwords-webextension#4]
```
The password list could not be retrieved.
Error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

I have actually been getting this error since the upgrade to the new Nextcloud passwords app, but it doesn't seem to effect the extension working.

I followed the debug steps and saw this in the console ([domain] replaces my valid NC domain):
`Encoding response failed Request { method: "GET", url: "[domain]/index.php/apps/passwords/api/0.1/passwords", headers: Headers, referrer: "about:client", referrerPolicy: "", mode: "cors", credentials: "omit", cache: "default", redirect: "follow", integrity: "" } SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data  app.js:1:92256`

The error only appears if `Enable Legacy API` is disabled within NC, but as I said the extension appears to work correctly either way.

**Comment by marius-wieschollek** [comment]
If the error only appears with the Legacy Api disabled i'm pretty confident i know the issue:
The webextension does not implement the new api. If you turn the legacy api off, the extension will sooner or later stop working when the internal cache gets depleted.
There will be a version 2.0 of the app later this year which will use the new api, but right now i did not find the time for it.

**Comment by HanFox** [comment]
Fair enough, but I don't see that information that the Legacy Api must be enabled written anywhere.
