### ISSUE TITLE
Unable to use the webextension if two factor authentication is enabled

### ISSUE THREAD

**Issue by kisppaul** [marius-wieschollek/passwords-webextension#47]
### System Information
- Nextcloud Version: 15.0.5
- Passwords Version: 2019.3.0
- Browser and Version: Chrome 72.0.3626.121
We use Nextcloud 15.0.5 with the "Two-Factor TOTP Provider" app (version 2.1.2) enabled. A user who uses two factor authentication to log in into nextcloud, cannot use the passwords webextension. If the same user disables two factor authentication, then there is no problem.

**Comment by marius-wieschollek** [comment]
If you use two factor authentication you need to use an app password for the web extension.

**Comment by kisppaul** [comment]
Thank you for your swift reply. Creating an app password solved our problem! Thanks
