### ISSUE TITLE
Unable to login with the firefox mobile extension

### ISSUE THREAD

**Issue by G4dter** [marius-wieschollek/passwords-webextension#48]
Hi,

I just installed the nextcloud App. No problem, it's perfect.
After that, i installed the Firefox extension. No problem, works great !
At the end, i installed the Firefox extension on my mobile. But there, it is impossible to login.

In the nextcloud logs, i see "Login failed" but i'm sure of my password, of course ...

All apps are up to date.

Do you have any explanation ?

Thank you and great job for all of that by the way :+1: !

Gaëtan

**Comment by marius-wieschollek** [comment]
Make sure to install the latest version of the extension. If you're sure that your password is correct but it does not work, try using an app password.

**Comment by fyah** [comment]
Hi,
I faced the same problem
Solution: type your nextcloud password somewhere else in clear, then copy it and past it in the extension config

don't know why it did the trick, but it did...

**Comment by GitHubGeek** [comment]
Facing similar login issue here:

1. Installed extension on 2 Firefox instances (desktop and mobile) using app password
2. Disabled app password's file system access
3. All seemed to work fine for a while
4. I then re-enabled TOTP for my nextcloud account
5. Both extesions stopped working: `URL invalid or API disabled`

**Comment by marius-wieschollek** [comment]
@GitHubGeek If you use TOTP, you need to use a device password to connect with the extension.

See https://docs.nextcloud.com/server/latest/user_manual/user_2fa.html#using-client-applications-with-two-factor-authentication for details.

**Comment by GitHubGeek** [comment]
Thanks for your response @marius-wieschollek It was me disabling legacy API that caused the problem :sweat_smile:

**Comment by marius-wieschollek** [comment]
No feedback, closing ticket.
