### ISSUE TITLE
Nextcloud password stored as clear text

### ISSUE THREAD

**Issue by ldesgrange** [marius-wieschollek/passwords-webextension#5]
Hi,

I'm testing the Passwords Nextcloud app and this extensions, so far I really like them, they are easy to use, provide all the features I want except that this extension seems to store the Nextcloud user credentials as plain text on the local computer (in Firefox: `Profiles/XXX/browser-extension-data/ncpasswords@mdns.eu/storage.js`).

Is there any plan to encrypt that (with a `master password` or something else)?

Many thanks,

Laurent.

**Comment by marius-wieschollek** [comment]
The passwords app itself will get a master password. The extension was supposed to no longer store passwords locally in version 2 and later. But since they are stored that way, i will remove that now.

**Comment by marius-wieschollek** [comment]
The new version 1.5.0 removes the locally stored passwords. As soon as firefox adds an [api for the password manager](https://bugzilla.mozilla.org/show_bug.cgi?id=1357856) i will try to integrate that one.

Thanks for the hint.

**Comment by ldesgrange** [comment]
Cool thanks, but after deleting `ncpasswords@mdns.eu/storage.js`, updating the plugin to version 1.5.0 and configuring it again (Nextcloud host, username and password), the file `ncpasswords@mdns.eu/storage.js` re-appears and contains the password to the Nextcloud server: `{"version":10500,"password":"XXX","initialized":true}`

**Comment by marius-wieschollek** [comment]
I know, i'm waiting for the API to be finished: https://developer.mozilla.org/en-US/docs/Web/API/Credential_Management_API . I recommend using an app password instead of the real password
