### ISSUE TITLE
Basic Authorization Support

### ISSUE THREAD

**Issue by WisdomCode** [marius-wieschollek/passwords-webextension#54]
The support for filling into basic auth would be nice. At the moment, when showing the login request in firefox, no interaction is possible, so maybe autofilling would be useful.

**Comment by marius-wieschollek** [comment]
It would be useful, but as a WebExtension i do not know of any way to access that window. If Firefox ever lands its [login api](https://bugzilla.mozilla.org/show_bug.cgi?id=1324919) for extensions we could just let the browser do it's thing but right now i do not see a way to support basic auth windows.

**Comment by WisdomCode** [comment]
It is possible with the passman extension. For their usage, please refer to this issue:
https://github.com/nextcloud/passman-webextension/issues/10
and to this script:
https://github.com/nextcloud/passman-webextension/blob/master/js/background/service/httpAuth.js
If you need help on that, I may assist you

**Comment by marius-wieschollek** [comment]
You can try this functionality with the developer build 2.1.0.3947

**Comment by marius-wieschollek** [comment]
But i now added a setting you need to enable before the extension does this.
Automatically responding to http basic auth requests could send credentials to untrustworthy servers.
