### ISSUE TITLE
text box confusion

### ISSUE THREAD

**Issue by moblesmarti** [marius-wieschollek/passwords-webextension#55]
Hi, and sorry if it is not the right place to explain this
I have found that when trying to use passwords in a web where before the password I have to choose a database, confusion is created and the user puts in the text box of the database and the password in the user.
Thanks for your job
![Captura de pantalla 2019-05-18 a las 17 18 33](https://user-images.githubusercontent.com/12881456/57973417-fc8bd580-79a8-11e9-9db6-c7641cc74bfd.png)

**Comment by marius-wieschollek** [comment]
@moblesmarti I assume the software is Odoo.

I have tried to reproduce it. In my case the database field is filled with the username and the password field with the password. 

I will include some patches to improve the user name field detection in the next version and also ignore readonly fields which should solve your issue.

**Comment by moblesmarti** [comment]
If it's Odoo!
Thanks for answer so soon
