### ISSUE TITLE
Exclude specific URLs

### ISSUE THREAD

**Issue by mb-bibi** [marius-wieschollek/passwords-webextension#57]
Hi,
because I never save highly important login data it would be nice not to get the note to save them each time I visit e.g. my bank account. The possibility to exclude definite URLs through a config item would be nice.
IMHO it's a minor proposal for the bottom of an existing todo-list but worth mentioned.
TIA
Martin

**Comment by marius-wieschollek** [comment]
@mb-bibi I think this is better suited for the webextension. We can add it since we have to rewrite the entire extension anyway.

**Comment by mb-bibi** [comment]
Hi Marius,
whereever you'll add the function, that you'll do it rewriting the webextension is great.
