### ISSUE TITLE
Streamline search

### ISSUE THREAD

**Issue by SyntaxErrol** [marius-wieschollek/passwords-webextension#58]
I think the search could be more accessible in a couple of ways:

1. Open the search tab by default on sites with no match
2. When the search tab is opened, automatically give focus to the text field
3. Listen for keyboard input (if possible) on the logins tab and go to search if there's any. So basically like the Windows 10 Start menu.

**Comment by marius-wieschollek** [comment]
All three things can now be done with the development version 2.0.0.3501

**Comment by marius-wieschollek** [comment]
This is now available in version 2.0.0.
