### ISSUE TITLE
Password not recognized

### ISSUE THREAD

**Issue by mokkin** [marius-wieschollek/passwords-webextension#59]
The Password / username is not recognized on this website:
https://www.carglass4partners.de/

Firefox 67.0.4
Extension: 1.9.1.0

**Comment by marius-wieschollek** [comment]
It seems like they are sending the form in a way that does not trigger an event. I will look into ways how logins like this can be detected.

**Comment by mokkin** [comment]
Here is another example:
https://portal.taxmaro.com/

**Comment by christianlupus** [comment]
I assume, this is another example: https://developer.ebay.com/signin

**Comment by marius-wieschollek** [comment]
Does this issue still exist with v2 of the extension?

**Comment by marius-wieschollek** [comment]
I'm closing this in favor of #123.
