### ISSUE TITLE
Can't Get Browser Extension to Connect

### ISSUE THREAD

**Issue by mikshepard** [marius-wieschollek/passwords-webextension#6]
I install this extension (v1.5.0) into Chrome, Opera, and Firefox.  I cannot sign into my Passwords account on any.  After entering my credentials and clicking "Save", I am moved to the first tab with "No logins found".  

I've tried this over https, with Passwords v2018.4.0-build2103 with Nextcloud 13.0.1, the Legacy API is enabled.

I've also tried this over https, on a separate off-site server with Passwords 3.0 on Nextcloud 13.0.1, the Legacy API is enabled.

Both are Debian Jessie servers.  Is this broken or am I missing something?

**Comment by marius-wieschollek** [comment]
Make sure that the to write the full server url like this `https://nextcloud.example.com` or `https://www.example.com/nextcloud` depending on how your Nextcloud is hosted.

If you click on the little spinning icon in the right upper corner you can let it refresh manually.

"No logins found" is the default text when no logins are found for the website you are on. You can use the second tab - the search tab - to check if logins were actually fetched.

**Comment by mikshepard** [comment]
Thanks, I was using the full server url, yes.  However doing the manual refresh seems to have solved the problem.  Feel free to close this out.

Thanks for your quick reply and help on this!  I really like the work on Passwords that you have done, I use it daily
