### ISSUE TITLE
Password Addon presents notification for detecting new credentials but storing does not work 

### ISSUE THREAD

**Issue by herrep** [marius-wieschollek/passwords-webextension#61]
Dear Marius,

Thank you very much for your great Nextcloud / Firefox / Password Tool.

I run Firefox 67.0.4 on MacOS High Sierra 10.13.6. When I browse to a website and enter new credentials, your addon detects my input and presents a notification according which I may click on this notification so that the credentials are automatically stored in Nextcloud.

I click on the notification, but nothing happens. The credentials are not added to Nextcloud.

I also use a Windows PC with Firefox. Under the Windows setup, your addon works as expected.

On my Mac, I am forced to manually store all passwords directly in Nextcloud, otherwise I cannot add new credentials.

Gladly I will provide further input for debugging if I coudl get some guidance what is required and how to obtain.

Best regards,
Peter

**Comment by marius-wieschollek** [comment]
Can you please open the address `about:debugging` in your Firefox. Then scroll to the Passwords extension and click "Debugging". A window opens where you can see the developer console.
Then go to a page where you can enter a new password to trigger the notification and confirm the notification. In the "Network" tab of the developer console an http request should appear and in the "Console" there should be an error message. Please check the error message and the status code of the http request.

**Comment by herrep** [comment]
Thank you very much for the precise guidance.

This is the http request when clicking on the notification that new credentials should be stored:

`https://<myserver>/index.php/apps/passwords/api/0.1/passwords
Anfragemethode:GET
Externe Adresse:<myipaddress:port>
Status-Code:
200
Version:HTTP/1.1
Referrer Policy:no-referrer-when-downgrade`

Here is the console output after clicking on the notification that new credentials should be stored:

`Request failed 
Request { method: "GET", url: "https://<myserver>/index.php/apps/passwords/api/0.1/passwords", headers: Headers, destination: "", referrer: "about:client", referrerPolicy: "", mode: "cors", credentials: "omit", cache: "default", redirect: "follow" }
 
Response { type: "basic", url: "https://s<myserver>/index.php/apps/passwords/api/0.1/passwords", redirected: false, status: 500, ok: false, statusText: "Internal Server Error", headers: Headers, body: ReadableStream, bodyUsed: true }
background.js:39:94233
Encoding response failed 
Request { method: "GET", url: "https://<myserver>/index.php/apps/passwords/api/0.1/passwords", headers: Headers, destination: "", referrer: "about:client", referrerPolicy: "", mode: "cors", credentials: "omit", cache: "default", redirect: "follow" }
 
Response { type: "basic", url: "https://<myserver>/index.php/apps/passwords/api/0.1/passwords", redirected: false, status: 500, ok: false, statusText: "Internal Server Error", headers: Headers, body: ReadableStream, bodyUsed: true }
 SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data" background.js:39:94342
Unchecked lastError value: Error: ID already exists: open-browser-action ExtensionCommon.jsm:679
Firefox kann keine Verbindung zu dem Server unter ws://127.0.0.1:5006/ aufbauen. background.js:155:21
Unchecked lastError value: Error: ID already exists: open-browser-action
ExtensionCommon.jsm:679
Firefox kann keine Verbindung zu dem Server unter ws://127.0.0.1:5006/ aufbauen. background.js:155:21
Die Verbindung zu ws://127.0.0.1:5006/ wurde unterbrochen, während die Seite geladen wurde. background.js:155:21
Unchecked lastError value: Error: ID already exists: open-browser-action ExtensionCommon.jsm:679
Firefox kann keine Verbindung zu dem Server unter ws://127.0.0.1:5006/ aufbauen. background.js:155:21
error occurred while processing 'sources: TypeError: can't access dead object
Stack: webExtensionTargetPrototype._allowSource@resource://devtools/server/actors/targets/webextension.js:293:5
TabSources/this.allowSource@resource://devtools/server/actors/utils/TabSources.js:25:39
_addSource@resource://devtools/server/actors/thread.js:1663:23
onSources@resource://devtools/server/actors/thread.js:1077:12
onPacket@resource://devtools/server/main.js:1291:58
receiveMessage@resource://devtools/shared/transport/child-transport.js:66:16
Line: 293, column: 5`

**Comment by marius-wieschollek** [comment]
Can you check if an error appears in the nextcloud log if you try to save a password?

**Comment by herrep** [comment]
Unfortunately, nothing shows up in the nextcloud log when I click onto the notification in order to save the password in nextcloud.

**Comment by herrep** [comment]
Are there any news on this issue? The password addon still works fine under Firefox/Windows, but I did not find a working solution under macOS.

**Comment by herrep** [comment]
The issue still persists. Are there any news on this issue? The password addon still works fine under Firefox/Windows, but I did not find a working solution under macOS.

**Comment by marius-wieschollek** [comment]
I haven't looked into this since. I'm currently rewriting the extension anyway so i'm spending less time on debugging the issues with the old extension.

**Comment by rgenoud** [comment]
Same here with Firefox 60.9.0esr on debian9.
Works with chromium. (and it works also on another debian9/firefox, but I can't find what's the difference).
Anyway, if a new extension is on the way, I'll wait for it.
Thanks !

**Comment by rgenoud** [comment]
I manage to make it work by using mate-notification-daemon instead of xfce4-notifyd

**Comment by marius-wieschollek** [comment]
With version 2.0.0 saving accounts can be done from the extension popup. this should "fix" the issue.
