### ISSUE TITLE
extension works in linux fails in windows

### ISSUE THREAD

**Issue by glenb77** [marius-wieschollek/passwords-webextension#62]
using in brave browser (fork of chromium) with nextcloud 16.03 archlinux package. password app in nextcloud working fine and can access through nextcloud url. extension works as expected when using browser in linux. same browser in windows login fails with message 'login crashed server'. can get to passwords app in windows. i did a packet capture of my lan at the router but i don't know what to look for. any help appreciated. thanks.

**Comment by marius-wieschollek** [comment]
Can you check the log of your nextcloud?

Go to https://[yournextcloud]/index.php/settings/admin/logging
Then try to save a password with the extension and check if a new entry (with app "passwords") in the log appears afterwards.
Then click "copy raw" and paste the result here

**Comment by glenb77** [comment]
issue solved by resetting password to nextcloud. now works as expected in brave browser on windows and linux across a few machines. thank you!
