### ISSUE TITLE
SSO connection in webexentension 

### ISSUE THREAD

**Issue by JulesBalgue** [marius-wieschollek/passwords-webextension#64]
Hi, 

is it possible to connect in SSO on the web extension? 
If no is this planned to fix it?
Thank you ! :) 

Jules

**Comment by marius-wieschollek** [comment]
We will add the option to connect the webextension to your Nextcloud with simply the QRCode or a link.

**Comment by edocod1** [comment]
Hello!
Are there any updates on this? We're using Social Login on our Nextcloud instance and we cannot login using the usual username and password, sadly

**Comment by marius-wieschollek** [comment]
If you're using the nightly version of the extension and add the urls of the pages manually in the app as custom field, you can already have a similar behaviour. Sadly i have currently not the time to work on the new extension, so it will take a while until i can add new features.

**Comment by paco-coutaud** [comment]
Hi !

We have the same issue.
We would like to have more info if possible on how we can map the password extension to a nextcloud account when using SSO.

We tried the following scenario:

With the new webextension (dev build) we tried to scan the QR Code provided in the "Security" section on a Nextcloud account to link the passwords webextension with it. It indicates "The QR code is not supported". Is there a workaround ?

I don't understand the "token" field as well ? How can we obtain a such token ?

Thanks in advance,
Paco

**Comment by marius-wieschollek** [comment]
> With the new webextension (dev build) we tried to scan the QR Code provided in the "Security" section on a Nextcloud account to link the passwords webextension with it. It indicates "The QR code is not supported". Is there a workaround ?

Follow the instructions in the first run wizard of the extension. The passlink qr feature needs a nightly version of the passwords app and is only available in the passwords app apps section.

> We don't understand the "token" field as well ? How can we obtain a such token ?

In the security section of the Nextcloud account right where you find that QR code you tried to use. Its the long string of characters generated by Nextcloud for the app. This token is also the correct way to connect the current (not dev) extension with a Nextcloud with SSO or 2FA enabled.

**Comment by paco-coutaud** [comment]
Hi !

Thanks a lot for your answer !

We wasn't able to have the first run wizard of the extension (nightly) to configure QR feature. We suppose we missed something... However, using token in the webextension when having SSO enabled works like a charm ! :)

**Comment by marius-wieschollek** [comment]
I see this as solved in version 2.0.0. See the [wiki](https://github.com/marius-wieschollek/passwords-webextension/wiki) for guides to link the extension to your nextcloud account
