### ISSUE TITLE
Passwords won't work with 2FA enabled

### ISSUE THREAD

**Issue by hari-bo** [marius-wieschollek/passwords-webextension#68]
When i enable the plugin Two-Factor TOTP Provider and 2FA on the user I can't connect with the Firefox Password plugin anymore. I've enabled the legacy API.
Is there an way to get 2FA working in combination with Nextcloud password?

I use Nextcloud 16.0.4 and Passwords 2019.8.1.

**Comment by marius-wieschollek** [comment]
Are you using an app password for the extension?

**Comment by hari-bo** [comment]
> Are you using an app password for the extension?

Excuse for the uncertainty this issue occurs with the Firefox plugin. When i open Nextcloud with an browser i can use 2FA.

**Comment by marius-wieschollek** [comment]
If you open Nextcloud with your browser and then go to settings and then Security there should be a section called "Devices and Sessions" (or similar). At the end of that section you can create a specific token or app password for apps which don't have 2FA.

**Comment by hari-bo** [comment]
> If you open Nextcloud with your browser and then go to settings and then Security there should be a section called "Devices and Sessions" (or similar). At the end of that section you can create a specific token or app password for apps which don't have 2FA.

Thanks, this is working! Will 2FA will be supported in future releases?

**Comment by marius-wieschollek** [comment]
yes, there will be 2FA in the future
