### ISSUE TITLE
auto log out

### ISSUE THREAD

**Issue by ChameleonScales** [marius-wieschollek/passwords-webextension#69]
It would be nice to have an option to automatically log out when I close the web browser. This way I would be sure that other people using the same machine don't have access to my vault.

**Comment by cptMikky** [comment]
I think this could go even a step further - on demand logout (i.e forget Master password), regardless what the browser status is. Call it a Panic button or something like that.

**Comment by marius-wieschollek** [comment]
@cptMikky That would be a separate issue. Feel free to open an issue for that.

@ChameleonScales @audioprog Any suggestion from where the timer should start? I would say the timer is reset every time the user does something in the extension popup. Or should i also include browser actions like changing tabs, navigating urls etc?

**Comment by ChameleonScales** [comment]
My suggestion was to log out every time I quit the web browser, not a time delay-based auto logout, but that could also be a good thing to have.
I like your first suggestion (restart the timer when you interact with the add-on). There are also right click context menu items for auto-fill and such. Maybe they should also restart the timer.

**Comment by marius-wieschollek** [comment]
> My suggestion was to log out every time I quit the web browser, not a time delay-based auto logout

This is already possible. With the latest version of the Nextcloud app, you can enable client side encryption in the settings. This will add the master password which needs to be entered every time you start the browser.

**Comment by ChameleonScales** [comment]
That's awesome! Right now I can't use it because it breaks the Android app but as soon as it catches up I'll enable it.
