### ISSUE TITLE
A problem with Nextcloud passman and Firefox

### ISSUE THREAD

**Issue by basti2015** [marius-wieschollek/passwords-webextension#7]
hello, I want to explain the problem in english.

I have install the app “passman” in Next Cloud and the Add on for firefox.

Now my problem is that a cant connect to the passman. I get the following popup: “Request has forbidden by Antivirus” - after I have disable that Kaspersky.
I get the following popup: JSON.parse:Unexpected character at line 1 column 1 of the JSON data.

Who can help me ? What must I do the solve the problems.

Firefox 59.02 + Nextcloud Passwords 1.5.0
Nextcloud 13.0.1

**Comment by marius-wieschollek** [comment]
This extension is only for the [Passwords App for Nextcloud](https://apps.nextcloud.com/apps/passwords). Passman is a different app and not compatible with this extension.

**Comment by basti2015** [comment]
OK Thanks. How can I install this app. the tar.gz file.

I have install the NextCloud on my FreeNas in a  separate jail

**Comment by basti2015** [comment]
Thanks again,
For install password i need:

PHP 7.1 or higher is required.

**Comment by basti2015** [comment]
Da ich gerade gemerkt habe das du aus Deutscland kommst, lass uns doch deusch schreiben

**Comment by marius-wieschollek** [comment]
ok

**Comment by basti2015** [comment]
Kann ich PHP 7 einfach so installieren ?

**Comment by marius-wieschollek** [comment]
Das kommt auf das Betriebssystem deines NAS an. Wenn Ubuntu oder ein Debian-Derivat darauf läuft, kannst du relativ auf PHP 7.1 umsteigen. Ältere PHP Software (Also Nextcloud und die Apps) sollte damit keine Probleme haben.
Wenn ich das richtig verstanden habe hast du ein FreeNas, da könnte dieser Forum Eintrag helfen: https://forums.freenas.org/index.php?threads/how-to-install-nextcloud-12-3-on-freenas-11-with-all-checks-passed.58634/

Wichtig ist für die App, dass es PHP 7.1 ist. PHP 7.0 fehlen leider ein paar Dinge, daher würde das nicht funktionieren.

**Comment by basti2015** [comment]
Nextcloud basiert auf FreeBSD

**Comment by marius-wieschollek** [comment]
Nextcloud basiert sicher nicht auf FreeBSD. Du meinst dein nas, oder?

**Comment by marius-wieschollek** [comment]
Das macht sinn. Da ich mit FreeBSD kaum Erfahrung habe würde ich die raten im Forum des Herstellers nachzufragen. Dort sollte man die erklären können wie du auf PHP 7.1 umsteigen kannst.
