### ISSUE TITLE
[Feature request] Autofill context menu item

### ISSUE THREAD

**Issue by ChameleonScales** [marius-wieschollek/passwords-webextension#71]
Some login pages only come in popup windows, but these windows don't have the add-on buttons on the top-left. Only add-ons with right-click items can be found there, so it would be nice to have a password auto-fill and even a password search button in the right-click menu.

**Comment by marius-wieschollek** [comment]
In version 2.0.0, suggested accounts can be pasted into the page from the context menu.

The search would be cool too, but right now i can't see a way to make this happen in a proper way. Right now that would mean adding a search form to the html of the page and sending the search results to the page. That means a malicious page would have an option to access/steal passwords using this functionality.

But i will see if i can make the option to open the extension popup work from popup windows.
Of course if someone can think of a different way to implement this, i would like to hear that too.

**Comment by ChameleonScales** [comment]
if the web extension allows for multiple urls on the same credentials then the search feature is less important.
