### ISSUE TITLE
Client Side Encryption support

### ISSUE THREAD

**Issue by WisdomCode** [marius-wieschollek/passwords-webextension#72]
I know this has been around for a while, but until now you closed them due to the ongoing progress in the nextcloud app. However, the nextcloud app supports client side encryption for around half a year by now, so updating the webextension to support this feature would finally make this progress available to a wider audience.

**Comment by marius-wieschollek** [comment]
I have started working on the new extension.
The development builds of the extension now support CSE and 2FA.

Firefox users can download the [XPI addon file here](https://git.mdns.eu/nextcloud/passwords-webextension/-/jobs/artifacts/testing/browse/dist/firefox-extension?job=Publish+Nightly+Firefox). This is a signed build of the testing branch which also gets automatic updates trough Firefox.
Chromium users will get an automated build later.

Currently recommendations work, the search works, pasting passwords work, you can have multiple accounts and it will refresh passwords from the server every 15 minutes.

Finding and saving new or updated passwords will be added in the next weeks.

If you do not have CSE now, but want to set it up, please use the 2020.2.0 nightly of the app.

The development builds of the extension are a work in progress and can contain bugs and incomplete features.

**Comment by cptMikky** [comment]
@marius-wieschollek do I understand correctly that the extension with CSE support is a different extension that the one without it? I'm thinking mostly regarding issue reporting so that I don't duplicate stuff.

Also, regarding the CSE: been testing it for a day and it's mostly working. CSE works with 2020.2.0 version of the app. 

The only CSE-related problem I see is that the extension doesn't remember the "master" password so I'm being asked to enter it a little bit too often.

**Comment by marius-wieschollek** [comment]
1. The extension is new for the source code, but has the same extension key. I will not continue or patch the old on anymore so you can just report issues here and just include that you're using v2.

2. I will try to implement a feature to save the master password later.

**Comment by marius-wieschollek** [comment]
Now the development version is also available on the [Chrome Web Store](https://chrome.google.com/webstore/detail/aipncmjoigmhooiiclcailmhiopachih)

**Comment by misterbridge** [comment]
> Now the development version is also available on the [Chrome Web Store](https://chrome.google.com/webstore/detail/aipncmjoigmhooiiclcailmhiopachih)

That's great, thanks, but for now there is neither anything when I click on the extenssion, nor on the extenssion's options:

![image](https://user-images.githubusercontent.com/7162404/72677441-d5882500-3a9c-11ea-8491-8a7c05a5d9a7.png)

**Comment by marius-wieschollek** [comment]
@misterbridge The version in the web store seems to have a bug in the initialization. I have already submitted but it is awaiting review.

You can just create new issues for any bugs.  just put in the version number. having every bug in one issue will be chaotic.

**Comment by marius-wieschollek** [comment]
Encryption is now supported with version 2.0.0. Encryption in the app will be enabled in the coming days.

**Comment by misterbridge** [comment]
Hi, thanks that's great !
#107 points to that issue mentionning master password, but I don't see it in the options of the v2.0.0 that I have.
Will it land later after all ?

**Comment by alephtaph** [comment]
Hi, thanks for the great app.
I can't find the option to auto lock as mentioned in #107. I would like to see auto lock when closing the browser or locking the computer and maybe an auto lock after 5, 10 or 20 minutes. In a corporate setting, it is a must, but maybe I just miss the option.
