### ISSUE TITLE
No login with 2FA enabled

### ISSUE THREAD

**Issue by sbr9150** [marius-wieschollek/passwords-webextension#76]
Hi,
I enable 2FA for security reason recently, Since then I lose connection with this extension. I set user/password then notification shows "error : invalid user credential" and server log shows `{"reqId":"bnU11bbjchyyAbwwQyNz","level":2,"time":"2019-12-16T07:41:10+08:00","remoteAddr":"xx.xx.xx.xx","user":"--","app":"core","method":"GET","url":"/editBlackAndWhiteList","message":"Login failed: 'admin' (Remote IP: 'xx.xx.xx.xx')","userAgent":"ApiTool","version":"17.0.1.1","id":"5df6c9c1be7e4"}`

In firefox debug I find 
`Request failed 
Request { method: "GET", url: "https://example.com/index.php/apps/passwords/api/0.1/passwords", headers: Headers, destination: "", referrer: "about:client", referrerPolicy: "", mode: "cors", credentials: "omit", cache: "default", redirect: "follow" }
 
Response { type: "basic", url: "https://example.com/index.php/apps/passwords/api/0.1/passwords", redirected: false, status: 401, ok: false, statusText: "Unauthorized", headers: Headers, body: ReadableStream, bodyUsed: true }`

Is there anything I can do except disable 2FA?

**Comment by marius-wieschollek** [comment]
Please use an app password.
