### ISSUE TITLE
Make the search work for substrings

### ISSUE THREAD

**Issue by godfuture** [marius-wieschollek/passwords-webextension#8]
Currently it seems that the search does not allow to search substrings. When my password has the name "My host - app1", I would like to find this entry by typing "app1" or "host" or "My". This could be applied to other fields as well, like tags or user.

V1.5.0

**Comment by marius-wieschollek** [comment]
This is definitely something i plan for the next major version (2.x). For the current version this is sadly not possible since it uses the legacy api which does not deliver password titles.

**Comment by d-tamm** [comment]
Currently the extension does not seem to search the name field. I have a password with "Unsere Fotos" as the name, but the search does not find it by typing any substring or the whole name. For me, the name field is the field identifying (in clear text) each password and should definitely be included in searches.
Also, the search currently seems to be case sensitive which (for me) does not make sense, specially not in conjunction with substring matching. In languages with composed terms (like German or Swedish), writing case can be subject to whether the term is part of a composed word or not (like "foto" in "Unsere Fotos" or "Familienfotos").

**Comment by marius-wieschollek** [comment]
This is now possible with the development version 2.0.0.3501

**Comment by marius-wieschollek** [comment]
This is now available in the stable version 2.0.0
