### ISSUE TITLE
[Feature request] allow disable autosubmit

### ISSUE THREAD

**Issue by cptMikky** [marius-wieschollek/passwords-webextension#81]
Using v2 extension when clicked on the login via context menu, the form gets filled *and* submitted.

I'd like to have an option to allow filling the form using this approach (or other approaches for that matter) without having the form submitted automatically.

Whether this should be a global settings or a per-site settings is probably up to discussion. I would personally prefer to have a customizable global default with per-site overrides but I understand that will probably be an overkill at this stage of implementation so just a global settings is what I would vote for at this point.

**Comment by marius-wieschollek** [comment]
I have recently implemented settings into the extension.
With build 3421, a global setting to disable the automatic submitting of login forms can be found in the extension settings in the tab "other settings"

A per-password or per-website setting may be added later if that is supported

**Comment by cptMikky** [comment]
I can see the build in the pipeline but Firefox still didn't update from 3417. As soon as it does, I'll test the feature.
