### ISSUE TITLE
Extension does not detect new password

### ISSUE THREAD

**Issue by francofunghi** [marius-wieschollek/passwords-webextension#82]
Hello.

Some time ago (sorry can not determine wehen exactly) my password extension in Chrome stopped detecting new passwords (eg on help.extcloud.com where i'm sure it worked). i'm on Chrome 79.0.3945.86 extension is 1.9.1.

All other feature work eg recognises saved passwords, copy of passwords ...

PAsswords App on NExtcloud is 2020.1.0-build3270.

Where should i look for errors ?

Regards Franz

**Comment by sgofferj** [comment]
Same on Firefox 72.0.2 / Ubuntu 18.04 / KDE. Doesn't detect new passwords. Filling existing passwords via right click menu works.

**Comment by rwagnon** [comment]
I have this problem in Chrome and Firefox.  I discussed with a coworker who verified it works for him.  I've made sure that Chrome and Windows notifications are allowed and I've seen them for other extensions.

**Comment by marius-wieschollek** [comment]
Does this issue still exist with v2 of the extension?

**Comment by marius-wieschollek** [comment]
I will close this in favor of #123
