### ISSUE TITLE
focus on input when click search

### ISSUE THREAD

**Issue by markuman** [marius-wieschollek/passwords-webextension#83]
**Current Status**
When you click on "search", you must click a 2nd time into the input field, before you can start typing.

**Feature Description**
After a click on "search", the focus should automatically change to the input field.

**Additional context**

![autofokus](https://user-images.githubusercontent.com/3920157/75555003-bab1b480-5a3b-11ea-942a-a15d74532b04.gif)

**Comment by marius-wieschollek** [comment]
This has already been proposed in https://github.com/marius-wieschollek/passwords-webextension/issues/58 and is also already implemented in the v2 development builds
