### ISSUE TITLE
missing goto button

### ISSUE THREAD

**Issue by markuman** [marius-wieschollek/passwords-webextension#84]
**Current Status**
When you search credentials, it is impossible to get the relying url. You must go to your nextcloud instance, search for the item and copy the url.

**Feature Description**
There shoult be a "goto" button, next to "copy username" and "copy password", which opens the relying website in a new tab.

**Additional context**

![missinggoto](https://user-images.githubusercontent.com/3920157/75555249-2eec5800-5a3c-11ea-9c69-a3388bb602f7.gif)

**Comment by marius-wieschollek** [comment]
This sounds very similar to https://github.com/marius-wieschollek/passwords-webextension/issues/60 . If so please close this issue.

**Comment by markuman** [comment]
Yes.
