### ISSUE TITLE
Display user names if multiple accounts for same website

### ISSUE THREAD

**Issue by TtuxX** [marius-wieschollek/passwords-webextension#88]
Hello @marius-wieschollek :)

-----

**Few kind words**

First and before anything else, I would like to take the opportunity here to thank you for your all the work you have done and tell you how great your extension is ! 🎉 

It is beautiful, extremely intuitive, reliable, simple yet powerful and FOSS. 👍 
I use it every single day and it is the only password manager I am willing to use. It is the best password manager I could find out there that suited my security and usability expectations. 🥇 

Thank you so much for these extremely great pieces of software (the NC app and the webextension), for your time, for all the work you do, all the tireless contributions you bring to the community and for all the improvements and features you are working on and we are looking forward to use, such as E2E encryption.

Keep up your great work because I can tell you that you are making many very happy Passwords users each and every day!! ❤️ 

-----

**Current Status**:

The addon does not display the user name next to the website account name, whether it be in the suggestions or in the search section. This can create few user experience issues when, for example, a user has several accounts on the same website.

Currently, when a user has multiple accounts on the same website, he or she must somehow blindly copy and paste the username into the URL bar or a text editor to reveal it and verify that the username he or she is about to click on is the right one. If it's not the right one, the user should iterate and try again.
 
The search section works to find a specific username but one has to remember the username spelling and the search broadens up to more than just the target website.

Current display:

![image](https://user-images.githubusercontent.com/6570830/81917100-0a346500-95d5-11ea-8958-c5638e2f3054.png)

**Feature Description**:

It would be great for the user to directly see the username next to the account name, both in the Suggestions and in the Search sections.
The user would then be able to directly select the right account to log in with.

Mockup:

![image](https://user-images.githubusercontent.com/6570830/81918312-98f5b180-95d6-11ea-8020-f9eb289f3cfb.png)

**Comment by Burschi500** [comment]
Oh please add this! I came here for suggesting the exact same thing.

**Comment by marc25v** [comment]
+1 :  Also would love to see this feature implemented.  Its a real hassle clicking them one at a time "trial-and-error" style.

**Comment by ediazcomellas** [comment]
+1 : I really find it annoying to test which account is the correct one.  In fact, this does not need to be done only "if there are several accounts for the same website", but could be standard for all accounts. It does not reduce security and adds clarity.
