### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by Pisoko** [marius-wieschollek/passwords-webextension#9]
Hey Marius,

I've got a problem while setting up the firefox webextension.
After filling in the credentials and clicking on "save" the extension is switching to the first tab with status "no logins found".
If I want to store a password by clicking on the "New Login found" window the error I get is "The password could not be saved"
Is there a chance of investigate the thing with a log file or something like that?

Here some more information:
![nextcloud_webapp](https://user-images.githubusercontent.com/11957656/39740695-105f55bc-5297-11e8-86cb-19ef84e5ec14.PNG)  

![nextcloud_webapp2](https://user-images.githubusercontent.com/11957656/39740705-1c3f2d8a-5297-11e8-8b45-99d98bc7ecb4.PNG)  

![nextcloud_webapp3](https://user-images.githubusercontent.com/11957656/39740709-1f05e6b2-5297-11e8-97d8-aa4c5b2dfe5b.PNG)  

![nextcloud_webapp4](https://user-images.githubusercontent.com/11957656/39740712-204238be-5297-11e8-933c-48ba2129f2b5.PNG)

**Comment by marius-wieschollek** [comment]
Hi. You can do the following:
- Check if your settings are correct. If your Nextcloud is running in a subfolder, you need to put that in the url field.
- In Nextcloud the Legacy API must be enabled
- Click the reload button in the upper right corner ad check if an error is reported
- Restart your browser
- Check the Nextcloud log for errors
- [Debug](https://github.com/marius-wieschollek/passwords-webextension/blob/master/Contributing.md#debugging) the Extension

**Comment by marius-wieschollek** [comment]
There is a bug in the api used by the browser plugin which causes this issue. I have created an [issue on GitHub](https://github.com/marius-wieschollek/passwords/issues/46) to track this. A nightly with a bugfix is available and the stable version 2018.5.2 will solve this.

**Comment by Pisoko** [comment]
yes it is! thx a lot!
