### ISSUE TITLE
Make notifications for updated passwords less error prone

### ISSUE THREAD

**Issue by godfuture** [marius-wieschollek/passwords-webextension#98]
**Current Status**
When the addon detects changes, it shows a notification. Often I clicked on it by accident, or I simply wanted to hide it. The result was that the passwords were updated without my intention or awareness.

**Feature Description**
This situation could be improved, by moving the notification from window bottom to the addon icon. Users could be notified about an event and properly ask them for interaction e.g. confirming a password change or mark as read for info messages.

**Additional context**
Already now we have some kind of notification on the icon e.g. when there are recognized passwords. Maybe changing it to something more generic and the user has to click the icon to read more about the event itself. Or there is another hint for pending password change indicated with a red "+".

**Comment by marius-wieschollek** [comment]
I would say that this has been resolved with 2.0.0
