### ISSUE TITLE
Passwords in folder not found

### ISSUE THREAD

**Issue by Griefed** [marius-wieschollek/passwords-webextension#99]
The Chrome extension fails to find passwords stored in subfolders inside the NC app. Personally, I sorted my passwords in folders going by A, B, C etc., but that renders the extension useless for me (emphasis on me, because I probably stored my passwords in a way which is not intended for the extension to work) because the extension can't find any passwords with a folder structure.

### System Information
- Extension Version: 1.9.1
- Browser and Version: Google Chrome  85.0.4183.121
- Client OS and Version: Windows 10 Pro Version 2004

### Steps to reproduce
1. Store passwords in a folder inside the passwords app in NC
2. Install and configure the Chrome extension
3. Try searching for any password stored in a subfolder and observe none being found

### Expected result
I'd like the extension to search in folders and find passwords according to my search entry.

### Actual result
A message saying "No resulst" is displayed in the extension window.

### Notes

Is this intended, known or going to be changed, or should I start thinking about rearranging my passwords? 
Love your passwords manager and the idea of the browser extension. Keep up the good work!

Cheers,
Griefed

**Comment by marius-wieschollek** [comment]
This is not supposed to happen. The extension fetches all passwords regardless of folder structure.
Do you have any special feature like E2E enabled or the legacy api disabled?

**Comment by Griefed** [comment]
I had encryption enabled and just tried again, but with encryption disabled this time.
I've also tried with and without activated legacy api. No dice, unfortunately.
I do have a sneaking suspicion that it's because I've got 2FA activated for my account, so I guess the extension can't access my NC account due to the missing 2FA. Could that be the issue?

**Comment by marius-wieschollek** [comment]
If you use 2FA, you need to use an app password for the extension.
If you use E2E in the passwords app you need to use the nightly/beta build for the extension (links in the readme)
The current stable extension requires the legacy api to be turned on.

**Comment by Griefed** [comment]
Ah I see.
Setting up an App Password did the trick. For anyone stumbling across this in the future, here's how you access your passwords through the Passwords Extension if you have 2FA for your NC account enabled:

 
1.  Go to Settings -> Personal -> Security
2.  At the bottom, enter an App name in the `App name`-box and click `Create new app password`
3.  Use the username and password shown as login details for your Chrome Passwords Extension
4.  Enjoy!

Thank you very much for your help, marius-wieschollek. I wouldn't have figured it out without you.
